### ISSUE TITLE
【求助】Parse Error: other error: length limit exceeded

### ISSUE THREAD

**Issue by micross** [salvo-rs/salvo#1013]
salvo 0.74.3版本，当接口请求的json里面的字段长度比较大时候，出现解析错误的的情况。以下是复现代码：
```rust
use salvo::prelude::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Payload {
    image_base64: String,
}

#[handler]
async fn hello(req: &mut Request) {
    req.parse_json::<Payload>().await.expect("unsuccessful parse");
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().init();

    let router = Router::new().post(hello);
    let acceptor = TcpListener::new("127.0.0.1:5800").bind().await;
    Server::new(acceptor).serve(router).await;
}
```

接口传的数据是前端将图片进行base64编码后的字符串，大概有140kB
```json
{ 
  "image_base64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAA...."
}
```

**Comment by chrislearn** [comment]
你可以使用  https://docs.rs/salvo_core/latest/salvo_core/http/request/struct.Request.html#method.parse_json_with_max_size
这个方法，因为安全问题，有最大长度限制。

你也可以使用 https://docs.rs/salvo_core/latest/salvo_core/http/request/fn.set_global_secure_max_size.html  设置全局最大的安全大小。

你还可以通过中间件设置某个路由及子孙路由允许的最大安全大小 https://docs.rs/salvo_core/latest/salvo_core/http/request/struct.SecureMaxSize.html

自己可以根据需求灵活使用。
