### ISSUE TITLE
som help needed, posting json to salvo

### ISSUE THREAD

**Issue by jhjacobs81** [salvo-rs/salvo#103]
Hello,

I am very new to both Rust and Salvo, and i was hoping someone could point me into the right direction.

i have build a client that sends some data from BORG Backup in json to a web api. This is whats beeing send:
``` {"token": "some-authentication-token", "date": "20220801", "hostname": "\"hostname\"", "name": "\"videoserver-2022-08-01T04:00:01-vod\"", "original_size": "6629973649001", "repository_id": "\"8b7c8f3f50a639069ec9d19f3a675382\"", "compressed_size": "6472889824365", "files": "2421814", "duration": "487.036629"}```

now i need to post this to a web api and put it in a database. Can anyone point me in the right direction how i can use Salvo for this?

**Comment by chrislearn** [comment]
You can use diesel or sqlx to manipulate database.

If you use diesel, you should defined a struct `NewRecord` like this:

```rust
#[derive(Insertable, Serialize, PartialEq, Clone, Debug)]
#[diesel(table_name = records)]
pub struct NewRecord<'a> {
    pub token: &'a str,
    pub date: &'a str,
   ...
}
```

Define a handler like this:

```rust
#[handler]
pub async fn save_record(req: &mut Request) {
    let record: NewRecord = req.extract_json().await.unwrap();
   diesel::insert_into(records::table)
            .values(&record ).execute(&conn).unwrap();
}
```

You can reference this example, how to connect to db and query data: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/salvo/src/main_diesel.rs

**Comment by jhjacobs81** [comment]
my apologies for the late answer :) i overlooked the example in the examples directory, i think i can figure this out :)
