### ISSUE TITLE
Office Document BUG？

### ISSUE THREAD

**Issue by MacJayLee** [salvo-rs/salvo#108]
<img width="579" alt="D14A0384B19BAD966209EC227315AB9A" src="https://user-images.githubusercontent.com/38428395/182567546-c8e0405e-3d50-41ed-a1aa-7cc18ce2c63e.png">

Dose It should return an Option , Not a String ??

**Comment by chrislearn** [comment]
好的, 我改一下.

**Comment by MacJayLee** [comment]
> 好的, 我改一下.

感谢 我今天第一次用salvo 真的很好用 希望越来越好

**Comment by chrislearn** [comment]
谢谢肯定, 希望能降低大家学习和使用 Rust Web 框架的难度.
