### ISSUE TITLE
关于response设置header中的 Content-Disposition 无效的问题

### ISSUE THREAD

**Issue by MacJayLee** [salvo-rs/salvo#111]
<img width="894" alt="jietu" src="https://user-images.githubusercontent.com/38428395/182813287-9fade334-d169-45d0-b3fb-63961d6b84f9.png">

非常奇怪的问题

 当文件不存在时 就能返回正确的文件名 虽然内容是一个404的html文本 
当文件存在时  filename修改不起作用  返回的永远是response.txt
使我使用的姿势有问题吗？？？

**Comment by MacJayLee** [comment]
<img width="699" alt="jietu" src="https://user-images.githubusercontent.com/38428395/182820071-9afd05a1-cb12-4c09-9721-42b153704c2e.png">

我应该是找到正确使用姿势了 这样可以成功
虽然你提供了这样方便的方法 
但是我还是想问 上面通过对response设置  Content-Disposition  为何无效？
我的理解是这种方法应该是可以的  
如果有空请帮忙解答一下  谢谢！！

**Comment by chrislearn** [comment]
我修复了一下你测试看看.
之前是如果不发现这个文件啥也没做.
如果发现了这个文件, 除非你使用 Builder 里面的函数设置这个, 否则, 它会自动计算一个合适的 header, 而并没有关心你是否已经提前设置了这个 header.

**Comment by MacJayLee** [comment]
> 

刚刚重新更新了一下代码 测试过还是不行  没有生效  仍旧为inline

**Comment by chrislearn** [comment]
不可能哈, 已经更新过了. 你确定是用的 git 的地址而不是 crates.io 的?

**Comment by MacJayLee** [comment]
> 不可能哈, 已经更新过了. 你确定是用的 git 的地址而不是 crates.io 的?

可以了可以了 感谢  MY BAD
确实是从cratre.io拉下来的 ，依赖改成 salvo = ｛git = "xxx"｝就好了
第一次知道可以这么写  网上查到的 哈哈
话说crate.io什么时候会和git同步啊 ？是你主动更新吗？

**Comment by chrislearn** [comment]
是要我主动发版本才会更新

**Comment by chrislearn** [comment]
0.29.1 已发,
