### ISSUE TITLE
Feature: Add OpenAPI support

### ISSUE THREAD

**Issue by chrislearn** [salvo-rs/salvo#112]

**Comment by Murtuzakabul** [comment]
What is the plan? Generate from document or code scanning ?

**Comment by chrislearn** [comment]
Feature like this: https://github.com/juhaku/utoipa

**Comment by Murtuzakabul** [comment]
Do we really need to make it work for other frameworks also? I guess you mean to adopt the architecture from it only.

**Comment by shujaat-github** [comment]
I want to move from Poem to Salvo once this feature is added.

**Comment by shujaatak** [comment]
> Feature like this: https://github.com/juhaku/utoipa

When this feature will be implemented?

**Comment by chrislearn** [comment]
Not sure when it will start.

**Comment by MahdiBaghbani** [comment]
really waiting for this, salvo is already my favorite, but sometimes people want openapi + swagger with their api's and I have no choice but to use poem or rocket.

**Comment by josejachuf** [comment]
The idea it has is to integrate Utoipa to Salvo or make a new development based on Utoipa?

**Comment by josejachuf** [comment]
I am trying to use Utoipa [1]. I get the JSON (http://127.0.0.1:7878/api/api-doc/openapi.json), but I can't make serve_swagger work (http://127.0.0.1:7878/api/swagger-ui)

Please could anyone help me with this code [2]?
I put anything until I got an error in the compilation :)

[1] https://github.com/juhaku/utoipa
[2] https://github.com/josejachuf/salvo-todos-api

**Comment by josejachuf** [comment]
https://github.com/salvo-rs/salvo/tree/main/examples/todos-openapi

**Comment by chrislearn** [comment]
This is an example: https://github.com/salvo-rs/salvo/blob/oapi/examples/todos-oapi/src/main.rs
You can compare it with this example use utoipa: https://github.com/salvo-rs/salvo/blob/oapi/examples/todos-utoipa/src/main.rs

Current developing implemention is modified from utopia.
