### ISSUE TITLE
read ^^^^ method not found in `&mut salvo::Request`

### ISSUE THREAD

**Issue by jhjacobs81** [salvo-rs/salvo#114]
**Describe the bug**
i am trying to read json thats posted to my handler. the documentation on https://salvo.rs/book/basics/request/ says i should do it like so: ```req.read::<User>().await;```
but when i do this, the program wont compile due to the above error

**Comment by chrislearn** [comment]
I forgot to update document. 
This function has renamed to extract_body.
You can get latest api from here: https://docs.rs/salvo_core/latest/salvo_core/http/request/struct.Request.html#method.extract_body

**Comment by jhjacobs81** [comment]
Thank you again for the quick answer! this is indeed the solution :-)
