### ISSUE TITLE
Add support for listenfd

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#131]
**Is your feature request related to a problem? Please describe.**
Not possible to use on existing `std::net::TcpListener`.

**Describe the solution you'd like**
I prefer to use [systemfd](https://crates.io/crates/systemfd) when working on websites so it can reuse the tcp connection.

```bash
cargo install systemfd # install systemfd binary
systemfd --no-pid -s http::8080 -- cargo watch -x 'run'
```

```rust
use listenfd::ListenFd; // cargo add listenfd 

let mut listenfd = ListenFd::from_env();

let listener = if let Some(listener) = listenfd.take_tcp_listener(0).unwrap() {
    listener // this is std::net::TcpListener
} else {
    TcpListener::bind("127.0.0.1:8080") // this is salvo TcpListener
};
Server::new(listener).serve(router).await;
```

But this doesn't work since `TpcListener` from salvo and `std::net` are not compatible.

Would it be possible to support this use case?

**Comment by chrislearn** [comment]
Does this example meet your needs?
https://github.com/salvo-rs/salvo/blob/main/examples/with-listenfd/src/main.rs

**Comment by prabirshrestha** [comment]
Thanks for the quick response. That seems to work.

Could probably update the example to this instead in case folks want to get address from config or env vars.

```rust
use std::net::SocketAddr;

let addr: SocketAddr = "127.0.0.1:8080"
   .parse()
   .expect("Unable to parse socket address");
hyper::server::Server::bind(&addr)
```
