### ISSUE TITLE
SessionHandler should allow secret rotation

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#133]
This is useful for production apps where we can gradually rollout the secret.

```rust
let session_handler = SessionHandler::new(
  MemoryStore::new(),
  b"primary_secret",
  vec![b"fallback_secret1", b"fallback_secret2"]
);
```

You always sign with the primary secret but when decoding you try primary first and if it fails to decode use fallback secrets.

**Comment by chrislearn** [comment]
Add fallback secrets supports.

**Comment by prabirshrestha** [comment]
Thanks.
