### ISSUE TITLE
compression doesn't seem to work as expected

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#134]
Not sure if this is the expected or not but does seem weird that it doesn't behave as I thought it would. There are two bugs I found.

1. No compression when sending str.

```rust
#[handler]
async fn hello_world(res: &mut Response) {
  res.render("hello");
}

let router = Router::new()
  .hoop(extra::compression::brotli())
  .get(hello_world);
```

I see compression when sending file called `hello.txt` with contents `hello`.

```rust
let router = Router::new()
  .hoop(extra::compression::brotli())
  .get(extra::serve_static::FileHandler::new("./hello.txt"));
```

2. Doesn't read accept-encoding request header and always returns br since I set it as `extra::compression::brotli`. Do note that browsers can send accept-encoding which is comma separated (`accept-encoding: gzip, deflate, br`) as is usually the preferred encoding algorithm they expect but server can decide to return any.

```
curl -vv http://localhost:8080 -H 'Accept-Encoding: gzip'
```

```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.84.0
> Accept: */*
> Accept-Encoding: gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-disposition: inline
< content-type: text/plain; charset=utf-8
< last-modified: Mon, 05 Sep 2022 07:55:20 GMT
< etag: "6fbaf-6-6315ab68-1c107dc6"
< accept-ranges: bytes
< content-encoding: br
< transfer-encoding: chunked
< date: Mon, 05 Sep 2022 08:05:36 GMT
<
hello
```

I would had thought I would specify compress as just `compression()` instead of algorithm. By default it should register all 3 algorithms and based on the `Accept-Encoding` header it should compress accordingly. 

I was expecting it to work similar to trillium's implementation of compression handler which most of the other frameworks do too. https://github.com/trillium-rs/trillium/blob/4ece63c91f6394efef9f48cb060fe7b9a964ce3a/compression/src/lib.rs

**Comment by chrislearn** [comment]
1. You can set min_length, it send without compress if size is smaller than 1024.
2. auto detect by accept encoding header is added.

**Comment by prabirshrestha** [comment]
This was works as expected now. Thanks for the quick fix!

```rust
.hoop(
    extra::compression::CompressionHandler::new()
        .with_algos(&[
            extra::compression::CompressionAlgo::Brotli,
            extra::compression::CompressionAlgo::Gzip,
        ])
        .with_min_length(1),
)
```

Would it be possible to add support for controlling the algorithm? In the following case both always returns `gzip`.

```bashaccept-encoding: gzip, deflate, br
curl -vv http://localhost:8080 -H 'Accept-Encoding: br, gzip'
curl -vv http://localhost:8080 -H 'Accept-Encoding: gzip, br'
```

I would want to support all compression `gzip`, `deflate`, `br` but would like to default to brotli first as it is newer and the compression rate is far better and is used by default in popular websites such as google.com and facebook.com.

Ordering when passing weight does seem to work as expected but unfortunatly most browsers just pass the algos such as `accept-encoding: gzip, deflate, br`.

```
curl -vv http://localhost:8080 -H 'Accept-Encoding: gzip;q=1.0, br;q=0.8, *;q=0.1'
curl -vv http://localhost:8080 -H 'Accept-Encoding: br;q=1.0, gzip;q=0.8, *;q=0.1'
```

Might be we should be able to set a default quality value?

```rust
CompressionHandler::new()
  .with_algos(&[
    CompressionAlgo::Brotli,
    CompressionAlgo::Gzip,
  ])
  .with_default_quality_value(CompressionAlgo::Brotli, 1.0)
  .with_default_quality_value(CompressionAlog::Gzip, 0.9)
  .with_default_quality_value(CompressionAlog::Deflate, 0.8)
```

Could also support `.ignore_request_quality_value(true)` if one wants to ignore the request values sent by client and always use the server recommendation instead.

In the meantime would be good if you can release a new version to crates so can reference this without git repo.

**Comment by chrislearn** [comment]
1. When you define CompressionHandler, the algos order will be used if quality value is not found.
2. Add force_priority, you can set it to true when you want ignore request quality value and order.

**Comment by prabirshrestha** [comment]
Default works as expected. Thanks.
