### ISSUE TITLE
Book is not up to date

### ISSUE THREAD

**Issue by Murtuzakabul** [salvo-rs/salvo#135]
Found a code on the book

`#[derive(Serialize, Debug)]
struct User {
    name: String,
}
let user = User{name: "jobs"};
res.render(Text::Json(user));`

Seems like it is no longer working as with implementation of Piece, the Text::Json no longer accepts Serializable but a Piece. Probably there is missing implementation of Piece from Serializable.

**Comment by chrislearn** [comment]
Try this:
```rust
res.render(Json(user));
```
I will update the book.

**Comment by chrislearn** [comment]
Done
