### ISSUE TITLE
Add support for caching headers primarily ETag/LastModified/If-Non-Match

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#136]
I would like to set appropriate caching headers for any responses include html and apis besides file. This improves performance on slow network when fetching it again.

I would like to have similar feature to [trillium's caching-headers](https://github.com/trillium-rs/trillium/tree/main/caching-headers).

(In case you are wondering why I'm filing issue, I'm trying to port by blog from trillium to salvo https://github.com/prabirshrestha/rblog with the main reason being trillium not support first class error handling compared to salvo)

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
I can't seem to use this feature. Probably need to add the feature [here](https://github.com/salvo-rs/salvo/blob/main/salvo/Cargo.toml)?

```
cargo add salvo --features=caching-headers
    Updating crates.io index
      Adding salvo v0.33.0 to dependencies.
             Features:
             + caching-headers
             + cookie
             + test
             - acme
             - affix
             - anyhow
             - basic-auth
             - compression
             - cors
             - csrf
             - extra
             - full
             - jwt-auth
             - logging
             - native-tls
             - openssl
             - proxy
             - rustls
             - salvo_extra
             - serve-static
             - size-limiter
             - sse
             - timeout
             - unix
             - ws
error: unrecognized features: ["caching-headers"]
```

**Comment by prabirshrestha** [comment]
It is able to compile but don't think it is working as expected.

```rust
  let router = Router::new()
      .hoop(extra::caching_headers::CachingHeaders::default())
      .hoop(extra::compression::Compression::default())
      .get(hello_world);
```

I was expecting `curl -vv http://localhost:8080` to return `ETag` header in the response.

<img width="1001" alt="Screen Shot 2022-09-08 at 9 13 49 PM" src="https://user-images.githubusercontent.com/287744/189270749-560bff9d-ebaa-4eb7-a7a1-6f0c0d0161ef.png">

**Comment by chrislearn** [comment]
I fixed it, please check it again.

**Comment by prabirshrestha** [comment]
Did you push the changes? I see version 0.33.1 as the latest commit.

**Comment by chrislearn** [comment]
Please check again, version 0.33.2.

**Comment by prabirshrestha** [comment]
If it is uncompressed response it works. `curl -vv http://localhost:8080`.

As soon as I compress it doesn't work. `curl -vv --compressed http://localhost:8080`. Since most of the content html/css/js/json api are compressed it should support etags when content is compressed.

**Comment by chrislearn** [comment]
Fixed

**Comment by prabirshrestha** [comment]
Everything now works as expected. Thanks for fixing the bugs along the way!

Feel free to release a new version so I can consume it directly from crates.io
