### ISSUE TITLE
add example for sending a file via NamedFile/NamedFileBuilder

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#137]
Examples include using static DirHandler but it would be good to have an example for NamedFile. I had to dig in the source code to see how it was used.

```rust
#[handler]
async fn get_file(req: &mut Request, res: &mut Response) -> anyhow::Result<()> {
  let path = "./file.txt";
  let file = NamedFile::open(path).await?;
  file.send(req.headers(), res).await;
  Ok(())
}
```

Also might be worth adding docs so can see an example without looking at the source code at https://docs.rs/axum/0.2.3/axum/response/struct.Redirect.html#.

**Comment by chrislearn** [comment]
I appreciate if you can give a PR :)
Doc repository: https://github.com/salvo-rs/website

**Comment by chrislearn** [comment]
Added fn `send_file` to `Response`.
