### ISSUE TITLE
redirect temporary seems to doing redirect permanent internally

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#138]
redirect temporary seems to doing redirect permanent internally. https://github.com/salvo-rs/salvo/blob/0fb3099242e2d432bb59c680aa28ffba62fbebcc/core/src/http/response.rs#L358-L359

Might be better to expose apis similar to axum instead? i.e. `redirect_temporary`, `redirect_permanent`, `redirect_found`, `redirect_to`.

https://docs.rs/axum/0.2.3/axum/response/struct.Redirect.html

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
Thanks for the quickfix.
