### ISSUE TITLE
expose KnownHeaderName enum

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#144]
It is very easy to make spelling mistake when using header names. It will be good to have a enum of KnownHeaderName that can be easily referenced. Reference: https://github.com/trillium-rs/trillium/blob/4ece63c91f6394efef9f48cb060fe7b9a964ce3a/http/src/header_name.rs#L199-L348

**Comment by chrislearn** [comment]
You can use `typed_insert`:

```rust
use salvo::http::headers::*;

res.headers_mut().typed_insert(etag);
```

**Comment by chrislearn** [comment]
All header name can be found here: https://docs.rs/salvo_core/latest/salvo_core/http/header/index.html
Typed headers can be found here: https://docs.rs/headers/0.3.8/headers/index.html
