### ISSUE TITLE
add middleware to force trailing slash or to remove trailing slash

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#148]
Similar to https://echo.labstack.com/middleware/trailing-slash/.

Some blog sites forces trailing slash and some doesn't. In order to maintain SEO as I move moved from an old blog framework I would like to force trailing slash or remove it.

Forcing trailing slash also makes markdown just work for blogs. For those navigating to `http://localhost:8080/posts/welcome/` with the `welcome/article.md` one could write `![image](image.png)` which is in `welcome/image.png` folder and it would correctly render the image `http://localhost:8080/posts/welcome/image.png`.

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
This works. Though I think it should be named `trailing_slash` instead of `tailing_slash`.

**Comment by prabirshrestha** [comment]
Thanks for renaming it to `trailing_slash`.

This is now working as expected.
