### ISSUE TITLE
proxying requests is very slow

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#149]
I'm proxing to [create-react-app](https://create-react-app.dev/) and I'm finding it very slow as it is taking several seconds.

<img width="1276" alt="Screen Shot 2022-09-11 at 12 09 57 PM" src="https://user-images.githubusercontent.com/287744/189544903-e93822d1-d0dc-4172-a891-771f27282162.png">

When directly hitting the site it is fast so definitely something with salovo's proxy implementation.

I didn't have the issue when using [trillium-proxy](https://github.com/trillium-rs/trillium/tree/main/proxy).

```rust
fn spa() -> Proxy {
    Proxy::new(vec!["http://localhost:3000".into()])
}

async fn make_service(config: AppConfig) -> AppResult<Service> {
    let router = Router::new()
        .hoop(extra::affix::inject(config))
        .hoop(extra::logging::Logger::default())
        .hoop(extra::compression::Compression::default().with_force_priority(true)) // Compression must be before CachingHeader.
        .hoop(extra::caching_headers::CachingHeaders::default())
        .push(Router::with_path("<**rest>").handle(spa()));
    Ok(Service::new(router))
}
```

**Comment by chrislearn** [comment]
I tested trillium and salvo, both are slow.
trillium:
![image](https://user-images.githubusercontent.com/5874864/189555188-a50cd166-6ed5-4ec5-9d6d-92ff8f201482.png)
Salvo:
![image](https://user-images.githubusercontent.com/5874864/189555197-8b6e9ea6-56fa-443b-8e6d-f9238703d338.png)

**Comment by prabirshrestha** [comment]
Hmm. Looking at the proxy.rs code it seems to create a new client for each request. What about setting the Client alongside `upstreams: Vec<String>`. Http supports [keep-alive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive) so it wouldn't require reestablishing connection for every request. Other option is to allow for an api to get the client. Might be this would help solve performance issues?

Currently I'm using only one `upstream` but when using multiple upstream could possible use some random numbers instead of locks or ask the user to provide a function to select the upstream and they could choose a lock free algorithm if needed.

**Comment by prabirshrestha** [comment]
Didn't see much perf improvement with reusing client. hyper already has keep alive settings enabled by default for 90 sec. https://docs.rs/hyper/0.12.13/hyper/client/struct.Builder.html

Hitting the create-react-app directly it usually takes 200ms but with proxy takes around 4sec. Probably would need to debug on server why it is taking such a long time.

Another option is to use other libraries such as reqwest. Here are some configs they have. https://github.com/seanmonstar/reqwest/blob/6ceb23958c8b6d7f1d8ee093f0ad73184d133d40/src/async_impl/client.rs#L141

**Comment by chrislearn** [comment]
Can you check example-proxy-react-app? It is very fast in my pc.
Or you can give me a slow example.
![image](https://user-images.githubusercontent.com/5874864/190065995-a9af41c6-ac6d-4a1f-8771-79c5246b65f8.png)
![image](https://user-images.githubusercontent.com/5874864/190066011-b23346b6-fe1a-435e-a7ca-b4cd3909571b.png)
