### ISSUE TITLE
Add first class support for embedding static content

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#150]
This is similar to the [trillium's static-compiled](https://github.com/trillium-rs/trillium/tree/main/static-compiled).

In debug mode I prefer to proxy to create-react-app and in prod mode I would like to embed the static files.

<details>
  <summary>Here is how I do it in trillium</summary>

Not a fan of trillium api as it still requires a lot of custom code to get a generic spa app working on dev/prod builds.

```rust
use trillium::Handler;

#[cfg(debug_assertions)]
pub fn spa() -> impl Handler {
    use trillium_tokio::TcpConnector;
    type Proxy = trillium_proxy::Proxy<TcpConnector>;
    Proxy::new("http://localhost:3000")
}

#[cfg(not(debug_assertions))]
pub fn spa() -> impl Handler {
    use trillium_compression::compression;

    (
        compression(),
        trillium_static_compiled::static_compiled!("$CARGO_MANIFEST_DIR/../client/build")
            .with_index_file("index.html"),
        |conn: trillium::Conn| async move {
            conn.with_header(
                trillium::KnownHeaderName::ContentType,
                "text/html; charset=UTF-8",
            )
            .ok(include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../client/build",
                "/index.html"
            )))
        },
    )
}
```
</details>

It will be great if salvo supports something similar. Instead of creating a custom one it could make sense to directly support rust-embed instead. rust-embed does seem to already have an example at https://github.com/pyrossh/rust-embed/pull/166/files.

```rust
#[cfg(debug_assertions)]
pub fn spa() -> salvo::extra::proxy::Proxy {
    salvo::extra::proxy::Proxy::new(vec!["http://localhost:3000".into()])
}

#[cfg(not(debug_assertions))]
pub fn spa() -> salvo::extra::rust_embed::RustEmbed {
    #[derive(rust_embed::RustEmbed)]
    #[folder = "../client/build"]
    struct Asset;

    salvo::extra::rust_embed::RustEmbed::new(Asset)
        .with_fallback_file("index.html") // this is needed such that any 404 will always render the spa app and spa can handle showing 404 page. by default this shouldn't be set. 
}
```

Reusing existing popular framework such as RustEmbed will probably allow to use the same `Asset` for other scenarios instead of potentially embedding the file twice.

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
Also probably worth adding rendering `Option<EmbeddedFile>` and `EmbeddedFile` in case one would like to use something like `res.render(Asset::get("favicon.ico"))`. This could be used for one of routes and we don't have to worry about correctly setting mime/etags and so on.

**Comment by prabirshrestha** [comment]
Also not sure if this is working as expected.

I have a create react app with `/` and `/signup` route.

```rust
#[derive(RustEmbed)]
#[folder = "../client/build"]
pub struct Assets;

pub fn spa() -> salvo::extra::serve_static::StaticEmbed<Assets> {
    salvo::extra::serve_static::static_embed::<Assets>().with_fallback("index.html")
}

let router = Router::new()
        .push(Router::with_path("<**rest>").handle(spa()));
```

When I go to http://localhost:8080 it works as expected. It renders the index.html download the js file. But when I go to `http://localhost:8080/signup` it render the salvo's default 404 instead of fallback index.html.
