### ISSUE TITLE
Serve Static middleware always returns a 200 status code

### ISSUE THREAD

**Issue by liaohongxing** [salvo-rs/salvo#156]
**Describe the bug**
Serve Static middleware always returns 200 status code, the first time should be 200 status code, the second time should be 304 status code. Always returning 200 takes up too much bandwidth

**Expected behavior**
The first time should be 200 status code, the second time should be 304 status code

**Additional context**
```rust
    let router = Router::new()
        .hoop(Logger)
        .push(
            Router::new()
                .path("assets/<**path>")
                .get(StaticDir::new(vec!["assets"])),
        );
```

**Comment by chrislearn** [comment]
This is a bug, I fixed it.

**Comment by liaohongxing** [comment]
thanks for the quick response, the issue has been resolved
