### ISSUE TITLE
Add support for flash message

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#158]
This is similar to one popularized by the ruby on rails. https://www.rubyguides.com/2019/11/rails-flash-messages/

rust counter parts:
- https://docs.rs/axum-flash/latest/axum_flash/
- https://lib.rs/crates/tide-flash
- https://github.com/LukeMathWalker/actix-web-flash-messages

Initially I'm looking to show flash message when the user sign up or resets the password.

Noticed that one of the sample using it but don't see how it is getting set in the rust world. https://github.com/salvo-rs/salvo/blob/9524d95dd7112dc598fec4ec12e88ad13a210fc9/examples/db-sea-orm/templates/index.html.tera#L5-L8

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
I'm having issues compiling the latest version of salvo.

```rust
    Blocking waiting for file lock on build directory
   Compiling salvo_extra v0.36.0
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
  --> /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_extra-0.36.0/src/force_https.rs:50:42
   |
50 |         if let Some(host) = req.header::<String>(header::HOST) {
   |                                          ^^^^^^ explicit generic argument not allowed
   |
   = note: see issue #83701 <https://github.com/rust-lang/rust/issues/83701> for more information
```


Disabling defeault-features doesn't seem to work either.

```toml
salvo = { version = "0.36.0", default-features = false, features = ["affix", "compression", "caching-headers", "logging", "proxy", "serve-static"] }
```

**Comment by prabirshrestha** [comment]
I also noticed that some crates use `_` while some use `-` for differentiator. Doesn't matter in code but wanted to mention it for consistency.

https://crates.io/search?q=salvo

**Comment by chrislearn** [comment]
https://github.com/rust-lang/crates.io/issues/728
Name can not be changed after they published. Hope it can be changed in future..

**Comment by chrislearn** [comment]
You need to upgrade your rust to latest version.

**Comment by shujaatak** [comment]
@prabirshrestha @chrislearn I think this issue can be closed now.
