### ISSUE TITLE
添加log中间件编译报错

### ISSUE THREAD

**Issue by flyGetHu** [salvo-rs/salvo#165]
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
  --> C:\Users\97078\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\salvo_extra-0.37.0\src\force_https.rs:54:42
   |
54 |         if let Some(host) = req.header::<String>(header::HOST) {
   |                                          ^^^^^^ explicit generic argument not allowed
   |
   = note: see issue #83701 <https://github.com/rust-lang/rust/issues/83701> for more information

**Comment by chrislearn** [comment]
Rust 1.64, 请确认你本地的 Rust 版本是否已经是最新稳定版.

**Comment by flyGetHu** [comment]
好的 我更新下

**Comment by flyGetHu** [comment]
ok,谢谢可以了
