### ISSUE TITLE
better defaults and 12 factor app support

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#167]
Make salvo easy to work with better defaults as mentioned in [12 factor app](https://12factor.net/)

Currently I need to do quite a bit of custom code to get salvo working to support better defaults.

```rust
pub async fn run() -> Result<()> {
    let mut listenfd = ListenFd::from_env();
    let (addr, server) = if let Some(listener) = listenfd.take_tcp_listener(0)? {
        (
            listener.local_addr()?,
            hyper::server::Server::from_tcp(listener)?,
        )
    } else {
        let addr: SocketAddr = format!(
            "{}:{}",
            std::env::var("HOST").unwrap_or("0.0.0.0".into()),
            std::env::var("PORT").unwrap_or("8080".into())
        )
        .parse()?;
        (addr, hyper::server::Server::bind(&addr))
    };

    tracing::info!("Listening on {}", addr);

    server.serve(make_service().await?).await?;

    Ok(())
}
```

Is is possible to support something like this. Most of the time I write sample small webapp and I spend too much time configuring initial salvo.

```rust
fn main() {
    trillium_tokio::run(handler);
}
```

With the above code I can just set PORT and HOST to change or can use the following config() if I need more configuration. It also automatically looks for listenfd.

```rust
fn main() {
    trillium_tokio::config()
        .with_host("::1")
        .with_port("8080")
        .run(handler);
}
```

By default I usually land up using `run()` but I can use `run_async` if I need to configure with others and await.

```rust
#[tokio::main]
fn main() {
    trillium_tokio::config()
        .with_host("::1")
        .with_port("8080")
        .run_async(handler)
        .await;
}
```

This makes trillium very easy to get started compared to salvo.

**Comment by chrislearn** [comment]
I think this hello world is also easy:

```rust
use salvo::prelude::*;

#[handler]
async fn hello_world() -> &'static str {
    "Hello World"
}
#[tokio::main]
async fn main() {
    let router = Router::new().get(hello_world);
    Server::new(TcpListener::bind("127.0.0.1:7878")).serve(router).await;
}
````

```rust
fn main() {
    trillium_tokio::run(handler);
}
```
Nobody will start a server without set host and port. It doesn't make much sense to give a default host and port.
