### ISSUE TITLE
Feature: deploying Salvo with shuttle

### ISSUE THREAD

**Issue by ivancernja** [salvo-rs/salvo#169]
Not really a feature request but more of a "get the word out" thing :)

I'm happy to announce that [shuttle](https://github.com/shuttle-hq/shuttle) has added support for deploying apps built with Salvo.
This decision was made upon receiving constant positive feedback about Salvo from our community :)

In short, shuttle lets users deploy their Rust apps by simply adding an annotation and running the `deploy` command, for free.

We have a `hello-world` example w/ Salvo that can be tried out here: https://docs.shuttle.rs/guide/salvo-examples.html 

Salvo team, if you like what you see, we'd appreciate if you could add it as a 'unofficial deployment platform', as part of the README. Our team will do its best to provide any kind of support to the users with getting Salvo apps up and running quickly.

Open for any questions and/or feedback! :)

**Comment by chrislearn** [comment]
I'm so excited about your support for salvo.  I have added shuttle's link  in the README and website.

**Comment by ivancernja** [comment]
> I'm so excited about your support for salvo. I have added shuttle's link in the README and website.

Happy to hear that!! :) And thanks so much for doing this on such a short notice! Again, if anyone from the community gets stuck or needs help or simply wants to hang out, you are more than welcome to pay us a visit :)
