### ISSUE TITLE
Create a simplified api to remove cookies

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#170]
`res.remove_cookie("name")` only removes from jar but not from http response. In order to remove cookies maxage must be set 0 with empty value.

Currently I need to write the following.

```rust
res.add_cookie(
    CookieBuilder::new("auth", "")
        .max_age(Duration::ZERO)
        .path("/")
        .same_site(SameSite::Strict)
        .http_only(true)
        .finish(),
);
```

Would be good if [make_removal](https://docs.rs/cookie/0.16.1/cookie/struct.Cookie.html#method.make_removal) was exposed as part of the `CookieBuilder` or at minimum should update the docs in `res.remove_cookie()` function. Had to look at the internal workings of it to know that `res.remove_cookie()` is not enough.

More info at https://docs.rs/cookie/0.16.1/cookie/struct.CookieJar.html#method.remove

**Comment by chrislearn** [comment]
Response created a new CookieJar in current version.
Will this bug fixed if Response's cookiejar is cloned from the request cookiejar?

In future version, we may move cookie future to salvo_extra crate.

**Comment by prabirshrestha** [comment]
When I login I set the jwt auth cookie with `path:/`.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/287744/196320438-8acfcb90-da45-4594-ba73-b441d0d6f9a0.png">

but when I use `res.remove_cookie(auth.to_owned());` it doesn't include the path.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/287744/196320667-31b74bb7-dbd3-4c60-a200-d7a29d26ad70.png">

While this might work on certain cases it won't work for all cases.

https://docs.rs/cookie/0.16.1/cookie/struct.CookieJar.html#method.remove
> To properly generate the removal cookie, cookie must contain the same path and domain as the cookie that was initially set.

I never expect `res.remove_cookie("name")` to work in any framework. One must explicitly send a cookie with max-age of 0 with path and domain if it was included when the cookie was created. I think just adding doc on `res.remove_cookie()` would be enough and no code fixes are required.

Unfortunately cookies in general are very error prone if you don't set the path and domain.

**Comment by chrislearn** [comment]
I will add description to document.
