### ISSUE TITLE
How to specify the sarting thread count ?

### ISSUE THREAD

**Issue by toplinuxsir** [salvo-rs/salvo#175]
How to specify the sarting thread count ?

**Comment by driftluo** [comment]
you can use `#[tokio::main(flavor = "multi_thread", worker_threads = 10)]` to specify [tokio](https://docs.rs/tokio/1.21.2/tokio/attr.main.html#multi-threaded-runtime) runtime worker thread

or, you can use tokio + hyper to Build your own runtime configuration like this 

https://github.com/salvo-rs/salvo/blob/9c4b63fb1c93f08d622787acf4c142dd74fce2f4/crates/core/src/server.rs#L55

**Comment by toplinuxsir** [comment]
@driftluo  Thanks   how to dynamicly specify the thread count ?

**Comment by driftluo** [comment]
> The worker_threads option configures the number of worker threads, and defaults to the number of cpus on the system.

If you want runtime changes, this is an unsupported feature

**Comment by josejachuf** [comment]
> you can use `#[tokio::main(flavor = "multi_thread", worker_threads = 10)]` to specify [tokio](https://docs.rs/tokio/1.21.2/tokio/attr.main.html#multi-threaded-runtime) runtime worker thread
> 

Hi,
This works? How can I check it?
