### ISSUE TITLE
Add support for more-di

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#176]
It would be great if there is an IoC library support. Looking at most of the libs in rust seems like [more-di](https://lib.rs/crates/more-di) is the only one I could find that supports the needs. It has concept of scopes allowing to create new instance per request which can be useful for db transactions. I prefer to have something like `user_service.signup("username", "password").await?` such that I can change the implementation easily in the future from db to micro services via rpc.

**Comment by chrislearn** [comment]
Closed as it i
