### ISSUE TITLE
Write status error

### ISSUE THREAD

**Issue by sysmat** [salvo-rs/salvo#177]
**Is your feature request related to a problem? Please describe.**
Is it possible to write response with HTTP status code and body as json(by default is html)

**Describe the solution you'd like**

```rust
res.set_status_code(StatusCode::NOT_FOUND)
     .render(Json(e))
```

**Describe alternatives you've considered**

**Additional context**
I'm new to salvo, using doc: https://salvo.rs/book/core/response/#write-status-error

**Comment by chrislearn** [comment]
Error format is depend on your request's accept content type.
When your request's accept content type is json, the returns page is json.
Default error pages supports page format: xml, plaintext, json, html.

**Comment by sysmat** [comment]
@chrislearn thx, that is great
