### ISSUE TITLE
More documents

### ISSUE THREAD

**Issue by Eliot00** [salvo-rs/salvo#18]
考虑添加一下贡献指南吗？还有Issue模板之类的文档
Consider adding a contribution guide? And some documents such as Issue templates

**Comment by chrislearn** [comment]
好的，这两天我加一下。文档的话，我也在逐步更新。尽量多抽点时间多写点。有啥想法都欢迎提出。

**Comment by chrislearn** [comment]
> 还有，加一下changeLog吧？，新的版本releaseLog也没有，不知道更新了什么

好的，后面的版本会添加。

**Comment by driftluo** [comment]
If you feel that all the current examples are not enough, you can move to see this [project](https://github.com/driftluo/myblog), I think basically all the available functions have been used, and have been completed online
