### ISSUE TITLE
http 2 protocol

### ISSUE THREAD

**Issue by sysmat** [salvo-rs/salvo#181]
**Is your feature request related to a problem? Please describe.**
salvo support HTTP 2 version?

**Describe the solution you'd like**
- salvo = {version = "0.37.1", features = ["basic-auth", "test"]}
- my client k6 upgrades the connection to HTTP/2.0 but salvo response is HTTP/1.1

**Describe alternatives you've considered**

**Additional context**

**Comment by chrislearn** [comment]
Did you tested it in your local browser?

**Comment by sysmat** [comment]
No with k6 for load, stress, ... tests, https://k6.io/docs/using-k6/protocols/http-2/

**Comment by sysmat** [comment]
- I try with chrome browser and also HTTP 1

![salvo_http1_chrome](https://user-images.githubusercontent.com/69830/197973067-b3009eda-0dc1-4705-bce4-6c07c25f1feb.png)

**Comment by sysmat** [comment]
- main:

```rust
let listener = TcpListener::bind("127.0.0.1:7878");
Server::new(listener).serve(route()).await;
```

- route:

```rust
fn route() -> Router {
    let auth_handler = BasicAuth::new(Validator {
        db: "mana".to_string(),
    });

    Router::with_path("api")
        .get(ping)
        .push(Router::with_path("user").hoop(auth_handler).hoop(Logger).get(get_user)
           .push(Router::with_path("<id>").get(get_user_by_id))
       )

}
```

- auth:

```rust
#[async_trait]
impl BasicAuthValidator for Validator {
    async fn validate(&self, username: &str, password: &str) -> bool {
        true
    }
}
```

```rust
#[handler]
pub async fn get_user_by_id(req: &mut Request, res: &mut Response) {
    let id = req.param::<i32>("id").unwrap();
let u =   user {
        id: 1,
        username: "sabin"
    }
    res.render(Json(u))
}

```

**Comment by chrislearn** [comment]
You need to use RustlsListener or other Tls Listener, You are using scheme HTTP, this is not supports Http2.

**Comment by sysmat** [comment]
-  Tls Listener I find in crate
- RustlsListener  don't find anything

**Comment by chrislearn** [comment]
You need to enable it in Cargo.toml. 
```toml
salvo = {features=["rustls"]}
```

**Comment by sysmat** [comment]
- @chrislearn thx
- I find it in https://github.com/salvo-rs/salvo/blob/main/examples/rustls/src/main.rs

**Comment by sysmat** [comment]
@chrislearn thx again

**Comment by sysmat** [comment]
- where is features=["rustls"], is it moved to another crate?

**Comment by chrislearn** [comment]
rustls is not moved to another crate. 
https://github.com/salvo-rs/salvo/blob/010fa46335e24995df1297e63904f04de5e8cee3/crates/salvo/Cargo.toml#LL28C14-L28C14

**Comment by sysmat** [comment]
what then to another module?

**Comment by sysmat** [comment]
- `use salvo::listener::rustls::{Keycert, RustlsConfig};` there was before 
```toml
salvo = {version = "0.37", features = ["basic-auth", "test", "logging", "rustls"]}
```
- salvo = {version = "0.40", features = ["basic-auth", "test", "logging", "rustls"]} is where

**Comment by sysmat** [comment]
- in 0.40 `use salvo::conn::rustls::{Keycert, RustlsConfig};`
- but then I get strange errors with http2

```rust
let config = RustlsConfig::new(
        Keycert::new()
            .with_cert(include_bytes!("../certs/cert.pem").as_ref())
            .with_key(include_bytes!("../certs/key.pem").as_ref()),
    );

    let acceptor = TcpListener::new("127.0.0.1:7878")
        .rustls(config)
        .bind()
        .await;

    Server::new(acceptor).serve(route()).await; 
```

- in postman `Parse Error: The server returned a malformed response`
- in curl:  `Received HTTP/0.9 when not allowed`

- this very confusing

**Comment by chrislearn** [comment]
salvo::conn::rustls


You can found it if you search it on docs.rs.

**Comment by sysmat** [comment]
listener -> conn

**Comment by sysmat** [comment]
salvo::conn::rustls results to

No results :(
Try on [DuckDuckGo](https://duckduckgo.com/?q=rust%20conn%3A%3Arustls)?

Or try looking in one of these:

**Comment by sysmat** [comment]
- https://github.com/salvo-rs/salvo/blob/main/examples/tls-rustls/src/main.rs
- this example dosent use RustlsListener, I try with exaple but getting strange http2 errors

`ERROR salvo_core::server: http serve connection failed error=Custom { kind: Other, error: "http2 error: connection error detected: unspecific protocol error detected" }`

**Comment by sysmat** [comment]
- even on http port(http://127.0.0.1:7878) not working
- log
- 
`2023-05-02T15:09:18.155154Z ERROR salvo_core::server: http serve connection failed error=Custom { kind: Other, error: "received corrupt message" }
`
```
postman: Error: socket hang up
curl: (52) Empty reply from server
```

**Comment by sysmat** [comment]
- https://docs.rs/salvo/latest/salvo/prelude/struct.RustlsListener.html#method.new
 
Docs are very poor, what is inner?

**Comment by chrislearn** [comment]
Please check latest version in github main branch, I checked it and it works.

**Comment by sysmat** [comment]
- I also try: https://github.com/salvo-rs/salvo/blob/main/examples/tls-rustls/
- but the same bad result

```
2023-05-03T06:14:22.034998Z  INFO salvo_core::server: listening HTTP/2.0 on https://127.0.0.1:5800
2023-05-03T06:14:22.036707Z  INFO salvo_core::conn::rustls::listener: tls config loaded.

2023-05-03T06:14:39.007584Z ERROR salvo_core::server: http serve connection failed error=Custom { kind: Other, error: "http2 error: connection error detected: unspecific protocol error detected" }

2023-05-03T06:16:02.261637Z ERROR salvo_core::server: http serve connection failed error=Custom { kind: Other, error: "received corrupt message" }

```

**Comment by sysmat** [comment]
I have also REST API in many languages(java, kotlin, deno, js, ...) and all works fine with curl, postman, k6 and http 2 protocol

**Comment by sysmat** [comment]
- ok, with browsers it works

`2023-05-03T06:22:09.670380Z ERROR salvo_core::server: http serve connection failed error=Custom { kind: Other, error: "received fatal alert: UnknownCA" }`

- rustls which TLS version is using?

**Comment by chrislearn** [comment]
Please check it use git main branch, I think I fixed it.
