### ISSUE TITLE
Runtime certificate decision

### ISSUE THREAD

**Issue by ghost** [salvo-rs/salvo#184]
**Is your feature request related to a problem? Please describe.**
Kind of, we're looking for a way to pick a TLS certificate for the listener/server to use on runtime, so picking a specific certificate for a domain and such. I'm wondering if such feature is actually possible to produce and implement.

**Describe the solution you'd like**
Similar to libraries like certmagic, a decision function to be called when a certificate is requested and needed.

**Describe alternatives you've considered**
I've thought of using middlewares and such but since the TLS configuration is setup when the server is configured and booted up, that approach seems not to be possible.

**Comment by chrislearn** [comment]
If go can, so can Rust. But it needs time.

**Comment by chrislearn** [comment]
If you use RutlsListener, you can add many key certs:
https://docs.rs/salvo_core/latest/salvo_core/listener/rustls/struct.RustlsConfig.html#method.keycert

But this function is not tested, you can try and give feedback.

**Comment by hrryt** [comment]
We're looking for runtime certificate decision, unless this can be updated and recorded during runtime it is not what we're looking for. If all else fails, would it be possible to leverage the `RustlsListener` itself and build a custom version that supports what we're looking for.

**Comment by chrislearn** [comment]
You can use `RustlsConfig` to config tls for each server name. If you want more flexibility，you can implement `ResolvesServerCert` and use `ServerConfig` as RustlsListener's config.

```rust
pub(crate) struct CertResolver {
    fallback: Option<Arc<CertifiedKey>>,
    certified_keys: HashMap<String, Arc<CertifiedKey>>,
}

impl ResolvesServerCert for CertResolver {
    fn resolve(&self, client_hello: ClientHello) -> Option<Arc<CertifiedKey>> {
        client_hello
            .server_name()
            .and_then(|name| self.certified_keys.get(name).map(Arc::clone))
            .or_else(|| self.fallback.clone())
    }
}
```
