### ISSUE TITLE
cared_methods for CookieFinder should be set to AllMethods

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#186]
Any reason why `FormFinder`, `QueryFinder` uses `ALL_METHODS` but not `CookieFinder`? Was using jwt auth based on cookie and figured out that `POST` calls always returns unauthorized.

https://github.com/salvo-rs/salvo/blob/e1d7f16b9984e895e3f26e82e33ac8d63420bd41/crates/extra/src/jwt_auth/finder.rs#L174-L180

**Comment by chrislearn** [comment]
It should be ALL_METHODS, maybe I just forgot to change it.
