### ISSUE TITLE
Need update_user code sample on mongodb example

### ISSUE THREAD

**Issue by thisisbintang** [salvo-rs/salvo#189]
I'm just learning rust for the first time. I googled how to update user data but didn't find it. Please anyone can make an example of the code. Thank you

**Comment by mrxiaozhuox** [comment]
You want get user info from client?

**Comment by MasteryOfMastering** [comment]
`#[derive(Deserialize)]
struct UpdateUserRequest {
    username: String,
}

#[handler]
async fn update_user(req: &mut Request, res: &mut Response, depot: &mut Depot) {
    let body = req.parse_json::<UpdateUserRequest>().await;

    if let Err(_) = body {
        res.set_status_code(StatusCode::BAD_REQUEST);
        return;
    }

    let body = body.unwrap();

    let db = depot.obtain::<Database>().unwrap();

    let collection = db.collection::<User>("users");
    
    collection.update_one(doc! { "username": &body.username }, doc! { "$set": { "username": &body.username } }, None).await.unwrap();
}`

I hope this can help.
