### ISSUE TITLE
Expose basic auth functions without creating BasicAuth struct

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#206]
I need to write custom basic auth for my webdav where I want certain paths to be accessibly anonymously and some with auth. In order to do this I want to have `let (username, password) = basic_auth::parse_credentials(&req);` and `basic_auth::ask_credential(&mut res)`. Is it possible to expose these as functions that I can use directly? https://github.com/salvo-rs/salvo/blob/fe78cb388f1b06f645b361b3ec781f4167b802a1/crates/extra/src/basic_auth.rs#L47-L66

**Comment by chrislearn** [comment]
Done

**Comment by prabirshrestha** [comment]
Looks good. Will wait for the release.

**Comment by chrislearn** [comment]
Realesed
