### ISSUE TITLE
Proxy Compression Bug

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#207]
I have created a minimal repro so it is easier for you to try it out.

https://github.com/prabirshrestha/salvo-proxy-compression-bug

Basically when using compression with proxy there are issues which renders garbage instead of actual content. Could be double compression one on the proxy server by create react app and the other one by salvo?

Another potentially bug I found was that there is no `vary` header set when using compression so caching headers might not work.

This bug only repros in Safari on iphone and ipad. Chrome/firefox seems to be be able to handle this correctly so you might not repro it there. Might be non safari browser is smarter to autodetect dual compression and decompress it twice? I have not debugged it thoroughly so not sure if there is multiple compression happening or some other proxy settings that is creating this issue.

For future ref:

```rust
use salvo::prelude::*;

#[handler]
async fn hello() -> &'static str {
    "Hello World"
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().init();

    // CachingHeader must be before Compression.
    let router = Router::with_hoop(CachingHeaders::new())
        .hoop(Compression::new().with_min_length(0))
        .push(Router::with_path("/server").get(hello))
        .push(Router::with_path("<**rest>").handle(spa()));

    let acceptor = TcpListener::bind("0.0.0.0:7878");
    Server::new(acceptor).serve(router).await;
}

fn spa() -> salvo::proxy::Proxy<Vec<&'static str>> {
    salvo::proxy::Proxy::new(vec!["http://localhost:3000"])
}
```

Copy pasting caching-header example to the new repro doesn't seem to compile. I had to change `let acceptor = TcpListener::new("127.0.0.1:7878").bind().await;` to `let acceptor = TcpListener::bind("0.0.0.0:7878");` instead.

**Comment by chrislearn** [comment]
Please check, compression will skip if `Content-Encoding `already exists in response headers.

**Comment by prabirshrestha** [comment]
Verified it works after the patch. Thanks for the quick fix!
