### ISSUE TITLE
Supply depot parameter for `BasicAuthValidator::validate`

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#212]
Currently, `BasicAuthValidator::validate` only supplies `username` and `password`, and returning `true` will enter the handler for that request. However, before entering the handler, we want to record some information regarding the current account, such as account level, privilege, or something else we want to use in the handler. 

Change `async fn validate(&self, username: &str, password: &str) -> bool;` to `async fn validate(&self, username: &str, password: &str, depot: &mut Depot) -> bool;` would be helpful to implement these functions.

**Comment by chrislearn** [comment]
只更新主分支了，因为是破坏性更新，不打算在 hyper 1.0 之前再发不兼容的版本了。
