### ISSUE TITLE
Uploading req body as stream

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#214]
I'm looking to support uploading files but without `req.file()` since that uses the forms.

Is there some way to get a `ReaderStream` for the request body so I can use `tokio::io::copy(req_body, dest_stream)`?

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/blob/d00b3eb5206a17184ef05d8e17a6e69b52b32c09/crates/core/src/http/body/req.rs#L83-L94

`ReqBody` impl `Stream` in lastest code.

**Comment by prabirshrestha** [comment]
Doesn't seem to be implemented in release branch. Is it possible to release a new version with this support?

**Comment by prabirshrestha** [comment]
So I tried the main branch. How would I get `AsyncRead`?

```rust
#[handler]
pub async fn upload(req: &mut Request, res: &mut Response) {
    let mut file = File::open("foo.txt").await.unwrap();
    let mut body_reader = StreamReader::new(req.take_body());
    tokio::io::copy(&mut body_reader, &mut file).await.unwrap();
    res.set_status_code(StatusCode::OK);
}
```

```
let mut body_reader = StreamReader::new(req.take_body());
    |                           ^^^^^^^^^^^^^^^^^ the trait `From<Box<(dyn StdError + Send + Sync + 'static)>>` is not implemented for `std::io::Error`
```

**Comment by chrislearn** [comment]
Try to map stream error to `io::Error`, like:

```rust
let stream = stream.map(|result| result.map_err(|err| {
    std::io::Error::new(std::io::ErrorKind::Other, err)
}));
```

**Comment by prabirshrestha** [comment]
I have got it working by using the following code. Given that this is common is it possible to support `.into()` so it can easily convert it to `&mut Reader`?

this is the tokio::io::copy
```rust
    pub async fn copy<'a, R, W>(reader: &'a mut R, writer: &'a mut W) -> io::Result<u64>
    where
        R: AsyncRead + Unpin + ?Sized,
        W: AsyncWrite + Unpin + ?Sized;
```

This is now what I'm doing for file uploads.

```rust
let mut file = File::open("foo.txt").await.unwrap();
let mut body_reader = StreamReader::new(req.take_body().map(|result| {
    result.map_err(|err| std::io::Error::new(std::io::ErrorKind::Other, err))
}));
tokio::io::copy(&mut body_reader, &mut file).await.unwrap();
```

**Comment by chrislearn** [comment]
> So I tried the main branch. How would I get `AsyncRead`?
> 
> ```rust
> #[handler]
> pub async fn upload(req: &mut Request, res: &mut Response) {
>     let mut file = File::open("foo.txt").await.unwrap();
>     let mut body_reader = StreamReader::new(req.take_body());
>     tokio::io::copy(&mut body_reader, &mut file).await.unwrap();
>     res.set_status_code(StatusCode::OK);
> }
> ```
> 
> ```
> let mut body_reader = StreamReader::new(req.take_body());
>     |                           ^^^^^^^^^^^^^^^^^ the trait `From<Box<(dyn StdError + Send + Sync + 'static)>>` is not implemented for `std::io::Error`
> ```

I changed Stream `Item` to `Result<Bytes, IoError>`. This compile error should fixed.

**Comment by prabirshrestha** [comment]
Much better. This works too. Thanks!

**Comment by Hydrostic** [comment]
the code above cannot work since the signature of `poll_next` has changed into
```rust
type Item = IoResult<Frame<Bytes>>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
```
Is there a convenient way to make it into a `StreamReader`?

**Comment by Hydrostic** [comment]
> > the code above cannot work since the signature of `poll_next` has changed into
> > ```rust
> > type Item = IoResult<Frame<Bytes>>;
> > 
> >     fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a convenient way to make it into a `StreamReader`?
> 
> https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.map

thanks!
