### ISSUE TITLE
Affix middleware not compiling

### ISSUE THREAD

**Issue by MasteryOfMastering** [salvo-rs/salvo#215]
**Describe the bug**
If I try to use features=["affix"], the application does not compile
Error message:
...\salvo_extra-0.37.9\src\force_https.rs:54:42
   |
54 |         if let Some(host) = req.header::<String>(header::HOST) {
   |                                          ^^^^^^ explicit generic argument not allowed

**To Reproduce**
1. Copy the affix example
2. Cargo run

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by chrislearn** [comment]
Make sure you are using rust vesion 1.64+

**Comment by MasteryOfMastering** [comment]
Working now, thank you.
