### ISSUE TITLE
proxy is commented in main branch

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#221]
Proxy seems to be commented in main branch.

https://github.com/salvo-rs/salvo/blob/46c368d719ea18e1ec701dd007eb6c1c29ce672d/crates/salvo/Cargo.toml#L48

Sometime I like to take direct deps on github instead of crates so would be good to have proxy support in main branch. Also makes it easy to test new bug fixes and changes that have been in main but not released yet.

**Comment by chrislearn** [comment]
This module depends on hyper's `Client`, it has removed from hyper, and will implemented in `hyper-util`.

**Comment by prabirshrestha** [comment]
For now I have manually used reqwest to make proxy in my app since I only use it for create react app so it works.

**Comment by chrislearn** [comment]
It works in main branch now.
