### ISSUE TITLE
Cors with main branch

### ISSUE THREAD

**Issue by chrislearn** [salvo-rs/salvo#223]
### Discussed in https://github.com/salvo-rs/salvo/discussions/222

<div type='discussions-op-text'>

<sup>Originally posted by **josejachuf** January 17, 2023</sup>
Hi

I changed the 0.37 branch to that of the repository

`salvo = { git = "https://github.com/salvo-rs/salvo.git", features = ["affix", "jwt-auth", "cache", "session", "cors"] }`

With this change, the middleware Cors stopped working. Now my front application shows Cors's error.  With version 0.37 it worked fine.

```
    let cors_handler = Cors::builder()
        .allow_any_origin()
        // .allow_origin("http://127.0.0.1:8000")
        .allow_methods(vec!["GET", "POST", "OPTIONS"])
        .allow_headers(vec![
            "CONTENT-TYPE",
            "content-type",
            "Access-Control-Request-Method",
            "Access-Control-Allow-Origin",
            "Access-Control-Allow-Headers",
            "Access-Control-Max-Age",
            "authorization",
            "Authorization",
        ])
        .build();

    Router::new().hoop(cors_handler).options(handler::empty())
```</div>

**Comment by chrislearn** [comment]
Can you give font error details? I have checked cors code, The main branch is same as 0.37.

**Comment by chrislearn** [comment]
You can try to put a wildcard match as the last router to the root router.

```rust
Router::new() // this is the root router
.push(
      Router::with_path("my_route")
          .post(my_handler)
  )
.push(
      Router::with_path("<**rest>")
          .hoop(cors_handler)
          .options(handler::empty())
  )
```

**Comment by josejachuf** [comment]
> ```rust
> Router::new() // this is the root router
> .push(
>       Router::with_path("my_route")
>           .post(my_handler)
>   )
> .push(
>       Router::with_path("<**rest>")
>           .hoop(cors_handler)
>           .options(handler::empty())
>   )
> ```
This works fine!! Thanks.

Instead of placing it at the beginning as I wanted, you used it at the end.
