### ISSUE TITLE
Page loads after the iteration instead of streaming the chunks

### ISSUE THREAD

**Issue by rtcq** [salvo-rs/salvo#224]
**Describe the bug**
When I am iterating through the chunks to call `res.write_body(chunk)` it does not immediately load the page and show the audio whose bytes are incoming; instead, the page loads when the loop is ended and all the downloaded chunks of the audio load.

**To Reproduce**
See the code

**Expected behavior**
The page should load as the first chunk arrives and gets attached to the response stream

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 108

**Additional context**
```rs
#[handler]
async fn stream(_req: &mut Request, res: &mut Response) {
  // ...
  res.add_header("Content-Type", "audio/mpeg", true).unwrap();
  res.add_header("Accept-Ranges", "bytes", true).unwrap();
  res.set_status_code(StatusCode::OK);
  while let Some(chunk) = download.next().await.unwrap() {
      println!("Chunk length: {}", chunk.len());
      res.write_body(chunk).unwrap();
      }
}
```

**Comment by chrislearn** [comment]
`write_body` will not send data to browser immediately. If  download's type is stream, you can use `res.streaming(download)`.
