### ISSUE TITLE
How to respond a memory file?

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#226]
`use salvo::fs::NamedFile` only supports building a file utility from a file saved on disks. However, in some cases, the file content is dynamically generated and saved in memory such as `Vec<u8>`, I don't want to first save the data to disk and then use `NamedFile` to send the file, which is inefficient. How to directly respond `Vec<u8>` as a file to the client?

**Comment by chrislearn** [comment]
1. Set `Response` headers such as `content-type`, `content-disposition`.
2. Use `Response::write_body` or `Response::streaming` to write your data to response.

**Comment by xmh0511** [comment]
> 

Thanks. Is there any detail document about how to use the second way(`Response::streaming`)?

**Comment by xmh0511** [comment]
> `NamedFile` use `Response::streaming` to write file: https://github.com/salvo-rs/salvo/blob/main/crates/core/src/fs/named_file.rs#L500-L530

I preliminary looked at the code, and the use is a bit complex. Is it possible to make `res.streaming` more ergonomic? Seems `res.streaming` uses chunk to respond the body. Can we make `res.streaming` just need to take any argument that implements `XXIterator`, then the method can internally control the loop according to the iterator.
