### ISSUE TITLE
Chunked size does not work

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#229]
In https://github.com/salvo-rs/salvo/blob/main/crates/core/src/fs/named_file.rs#L468, we set `length = self.metadata.len()`, which equals the file's length, and then we set chunked_size to `length` in https://github.com/salvo-rs/salvo/blob/main/crates/core/src/fs/named_file.rs#L524. IIUC, the chunked_size will always equal the file's size if we don't use **range**(the variable length is not modified in the case). I test the case where the responded file has `4MB`(a plain text file), the file is just totally sent to the client without using chunk way.  

````rust
	let named_filed = NamedFile::builder("./test.txt");
	let Ok(mut file) = named_filed.build().await else{
		res.set_status_code(StatusCode::BAD_REQUEST);
		return res.render("No such file");
	};
	file.disable_content_disposition();
	file.send(req.headers(), res).await;
````

````
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
last-modified: Mon, 13 Feb 2023 09:04:29 GMT
etag: "3a41559-3f61e3-63e9fd1d-222b267f"
accept-ranges: bytes
content-length: 4153827
date: Mon, 13 Feb 2023 09:47:10 GMT
````

**Comment by chrislearn** [comment]
这个 chunked_size 应该是指整个文件的长度，结果应该是没有错的。后台是 stream 的方式读取部分数据发送，但是 content-length 需要标注为整个文件的长度。
回头我把字段名字啥的稍微改一下，可能叫 file_size 会更清晰点？

**Comment by xmh0511** [comment]
@chrislearn  

> 结果应该是没有错的

结果不对，我直接用`TcpStream`发送了一个get请求，服务器是直接将文件的所有内容都写到body里面的（没有通过chunk的方式），客户端测试程序
````rust
use std::{net::{TcpStream},io::{Error, Write, Read}};
fn main()->Result<(),Error> {
   let mut conn = TcpStream::connect("127.0.0.1:8080")?;
   println!("connection ok");
   let write_content = b"GET / HTTP/1.1\r\n\r\n";
   conn.write(write_content)?;
   println!("write ok");
   let mut vec = Vec::new();
   vec.resize(1024 * 1024, b'\0');
   let read_size = conn.read(& mut vec[..])?;
   println!("{read_size}");
   println!("{}",std::str::from_utf8(&vec[..read_size]).unwrap());
   Ok(())
}
````
返回的报文内容是
````
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
last-modified: Tue, 14 Feb 2023 01:50:57 GMT
etag: "3a41559-476781-63eae901-2cf7f4b1"
accept-ranges: bytes
content-length: 4679553
date: Tue, 14 Feb 2023 01:51:10 GMT

<!-- 
 * qiun-data-charts 秋云高性能跨全端图表组件 v2.3.7-20220118
 * Copyright (c) 2021 QIUN® 秋云 https://www.ucharts.cn All rights reserved.
 * Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
 * 复制使用请保留本段注释，感谢支持开源！
 * 为方便更多开发者使用，如有更好的建议请提交码云 Pull Requests ！
 *
 * uCharts®官方网站
 * https://www.uCharts.cn
.....
````
可以看到文件的内容在报头下面直接输出了。期望的chunk的回写方式是，头部有字段`Transfer-Encoding: chunked`并且body的内容应该满足一下形式
[chunk size][\r\n][chunk data][\r\n][chunk size][\r\n][chunk data][\r\n][chunk size = 0][\r\n][\r\n]

其中chunk size是以十六进制的ASCII码表示

**Comment by xmh0511** [comment]
是否能file.send(...)的时候指定通过Transfer-Encoding: chunked方式返回呢？对于大文件很有用

**Comment by xmh0511** [comment]
Transfer-Encoding: chunked 在浏览器渲染上渲染上有优化效果，比如文本，html等

**Comment by chrislearn** [comment]
https://stackoverflow.com/questions/13557900/chunked-transfer-encoding-browser-behavior

按这个帖子里的说法：

···
The browser can process and render the data as it comes in whether data is sent chunked or not. Whether a browser renders the response data is going to be a function of the data structure and what kind of buffering it employs. e.g. Before the browser can render an image, it needs to have the document (or enough of the document), the style sheet, etc. 
···

即使是不是 chunked 的，浏览器也会在恰当的时候开始提前渲染页面的，并不需要等待所有数据发送完毕。

**Comment by xmh0511** [comment]
> https://stackoverflow.com/questions/13557900/chunked-transfer-encoding-browser-behavior
> 
> 按这个帖子里的说法：
> 
> > The browser can process and render the data as it comes in whether data is sent chunked or not. Whether a browser renders the > response data is going to be a function of the data structure and what kind of buffering it employs. e.g. Before the browser can
> > render an image, it needs to have the document (or enough of the document), the style sheet, etc.
> 
> 即使是不是 chunked 的，浏览器也会在恰当的时候开始提前渲染页面的，并不需要等待所有数据发送完毕。

那么对存储在本地的文件是没有必要通过chunked方式返回并且目前在salvo中也不会以此方式返回了？对于内存中的数据，我似乎可以这么用
````rust
	let file = tokio::fs::read("./test.txt").await.unwrap();
	println!("len: {}",file.len());
	let chunk_iter = file.chunks(20);
	let mut que = VecDeque::new();
	for chunk in chunk_iter{
		que.push_back(chunk.to_owned().into());
	}
	res.add_header("content-type", "text/plain; charset=utf-8", true).unwrap();
	res.set_body(ResBody::Chunks(que));  // 这确实是chunked方式返回给客户端的
````

**Comment by chrislearn** [comment]
你这写法看上去挺好。个人感觉本地已知大小的文件没有必要用chunked方式返回.
