### ISSUE TITLE
Repose with a binary data

### ISSUE THREAD

**Issue by yamelsenih** [salvo-rs/salvo#231]
Exists a way for response a binary data?

Some like

```Rust
_res.payload(binary_to_response);
```

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/blob/716c9fc0c632f4473d08a47025d46488ce880305/crates/core/src/http/response.rs#L369

**Comment by yamelsenih** [comment]
Thanks @chrislearn this work
