### ISSUE TITLE
content-type header is being overwritten

### ISSUE THREAD

**Issue by Volkor3-16** [salvo-rs/salvo#233]
as part of a larger project, I am utilising nginx-sendfile with a `X-Accel-Redirect` header.
The idea of this header, is nginx will see that and load the static file directly, instead of getting the program to load it up, then pass it over a connection multiple times. Using this header speeds up file serving considerably.

However, with salvo, I am rendering a 'blank' page, expecting the only the headers to pass through to nginx. However when I render a blank page, with just the content-type and x-accel-redirect headers, the content-type I get back is always `text/plain` instead of the expected `image/png`

```rust
    if nginxsendfile {
        // Add the content-type header.
        res.add_header("Content-Type", "image/png", false).unwrap();

        // Add the header, and we're done.
        // X-Accel-Redirect lets nginx serve the file directly, instead of us doing all that hard work.
        let xsend = "/files/".to_string() + &filename.to_string();
        res.add_header("X-Accel-Redirect", xsend, true).unwrap();
        res.render("");
    }
```

when curling the url, I get the following

```
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< x-accel-redirect: /files/NpV4NZ.png
< content-length: 0
< date: Wed, 22 Feb 2023 13:59:56 GMT
```

If I change the name of the content-type header to something else, I can see both content-type and the new name.

I imagine that the salvo overwrites the content-type header, to match the body of the response.

Is this a bug? or am I misusing this, and there is a different way to do this?

I'm a beginner to rust, so I'm likely misusing a bunch of stuff.
If you need to see more code, see https://git.volkor.me/Volkor/Ephemeral/src/branch/main/src/main.rs#L168 for the full program.

(Thank you for making salvo, It has been a wonderful experience learning rust with!)

**Comment by chrislearn** [comment]
remove the last rendr(""). and set response status to 200.

**Comment by Volkor3-16** [comment]
oh my god, it /was/ something simple like that 

Tested and working fine, thank you so much!
