### ISSUE TITLE
Cache stored in redis

### ISSUE THREAD

**Issue by josejachuf** [salvo-rs/salvo#234]
Hi @chrislearn 
Can it be implemented that the cache use redis as store?

Thanks

**Comment by chrislearn** [comment]
It can, but depends on whether I have time to implement it, or someone can help to implement it.

**Comment by brunobell** [comment]
> It can, but depends on whether I have time to implement it, or someone can help to implement it.

If there is plan to implement redis cache store, I am willing to take this @chrislearn

**Comment by chrislearn** [comment]
@brunobell If you are free, please help to implement it. Thank you very much.
