### ISSUE TITLE
Run from docker is closed after request

### ISSUE THREAD

**Issue by yamelsenih** [salvo-rs/salvo#235]
I try run it over a docker command but after the first request to service the docker image is down...

Some info?

My docker image is based from [Rust official image ](https://hub.docker.com/_/rust), basically is the folow:

```Shell
FROM rust:1.67 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
```

I add some println for endpoints and it is printed but the docker image is shutdown after run, is like the server was ended instead await ever

Best regards

**Comment by chrislearn** [comment]
It seems not salvo's problem, you should give more information about it, such as docker log or a minimum repository.

**Comment by yamelsenih** [comment]
I saw the problem.... Was a dependence of SO.

Thanks bro
