### ISSUE TITLE
TcpListener: possible outdated docs and examples?

### ISSUE THREAD

**Issue by MahdiBaghbani** [salvo-rs/salvo#238]
**Describe the bug**
Salvo example does not compile.

**To Reproduce**
1. Go to [compression example](https://github.com/salvo-rs/salvo/tree/main/examples/compression)
2. clone
3. compile
```rust
error[E0599]: no function or associated item named `new` found for struct `salvo::prelude::TcpListener` in the current scope
  --> api/src/lib.rs:23:33
   |
23 |     let acceptor = TcpListener::new("127.0.0.1:5800").bind().await;
   |                                 ^^^ function or associated item not found in `salvo::prelude::TcpListener`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `api` due to previous error

```

**Expected behavior**
compile successfully.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Rust: 1.67.0 stable
 - salvo = { version = "0.37", features = ["compression", "logging", "serve-static"] }
 - tokio = { version = "1.19", features = ["macros", "rt-multi-thread"] }

**Additional context**
searched through the issues found this: https://github.com/salvo-rs/salvo/issues/204#issuecomment-1364598690
fixes the issue! 

**My conclusion**
The `new` method on `TcpListener` is no longer working and we must use `bind`.
am I correct?

**Comment by chrislearn** [comment]
salvo 0.37 is the version released and published to crates.io. You can checkout branch 0.37.x to view it's examples.

The main branch is not published to crates.io and it is latest and supports HTTP3.
