### ISSUE TITLE
How is `WebSocket` seprated to reader and writer in the latest version?

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#243]
See https://gitee.com/hubert22/salvo-websocket/blob/main/salvo-websocket/src/websocket.rs#L104, 
````rust
let (ws_sender, mut ws_reader) = ws.split();
````
However, this method cannot be found in the latest version. How do we implement the group chat by ourselves?

**Comment by chrislearn** [comment]
```rust
salvo = { version = "0.36.0", features = ["extra", "anyhow"] }
```
I looks you use old salvo, you can check this example:
https://github.com/salvo-rs/salvo/blob/main/examples/ws-chat/src/main.rs

**Comment by xmh0511** [comment]
We should import `use futures_util::{FutureExt, StreamExt};` to make `ws` have the trait method `split`.

**Comment by xmh0511** [comment]
To let `WebSocket` has a method `split(self)->(reader, sender)` does make sense, instead of requiring traits in other crates. Currently, we need `futures-util` to do this.

**Comment by chrislearn** [comment]
import trait and let Websocket has this method is rust style.
