### ISSUE TITLE
Shared mutable state

### ISSUE THREAD

**Issue by ja3abuser** [salvo-rs/salvo#244]
Hello! I know there is an affix, but apparently it is not mutable, is it possible to do something similar on app_data in Actix? This would make it easier to work with databases and save information (e.g. counter of requests per second).

**Comment by chrislearn** [comment]
It use `Mutex`, you can use `Mutex` is salvo in the same way.

**Comment by chrislearn** [comment]
I have updated affix example: https://github.com/salvo-rs/salvo/blob/main/examples/affix/src/main.rs
