### ISSUE TITLE
curl + example-tls-openssl get an error: "connection error: not connected"

### ISSUE THREAD

**Issue by meilihao** [salvo-rs/salvo#271]
**Describe the bug**
curl via example-tls-openssl get error log: "connection error: not connected"

![2023-04-27_11-41-26](https://user-images.githubusercontent.com/4382586/234754039-4e8d22bb-c866-4978-bab3-e066596ce73e.png)

**Expected behavior**
no error log

**Env**
 - OS: openSUSE Leap 15.4
 - Browser: curl 7.79.1
 - Version: 0.38

**Comment by chrislearn** [comment]
Please check it in version 0.48.0, it should be fixed.

**Comment by meilihao** [comment]
test 0.48.2 is ok
