### ISSUE TITLE
gzip compression reduce throughput to much

### ISSUE THREAD

**Issue by Algorab** [salvo-rs/salvo#272]
I have a sse endpoint in salvo. This endpoint sends uncompressed roundabout 145000 sse messages per second. When I use the gzip compression the output is reduced to 72000 messages sse messages per seconds. Which is nearly 50% of the uncompressed throughput. No doubt gzip will have a cost, but 50%. 

I pick out the compression.rs and tried the encoder with Level::Fastest. But the throughput was the same. Is there bug or I do something wrong?

**Comment by Algorab** [comment]
Set a litte project which demonstrate the throughput reduction.
https://github.com/Algorab/salvo-sse-gzip

**Comment by chrislearn** [comment]
have you tested compression using other web framework, such as axum, actix?
I guess this is not web framework's problem.

**Comment by Algorab** [comment]
Yes I have tested with actix-web. It was roundabout 145000 uncompressed and roundabout 90000 in compressed mode. Which is ok for me. This values are in comparison to the first post.

**Comment by chrislearn** [comment]
@Algorab Can you share a axum test case?

**Comment by Algorab** [comment]
I have created a axum and an actix test cases. 
In short summary axum and salvo have a reduction on roundabout 70%, while on the other hand actix has a reduction of only 30%. See the readme file in the projects.

https://github.com/Algorab/salvo-sse-gzip
https://github.com/Algorab/axum-sse-gzip
https://github.com/Algorab/actix-sse-gzip

**Comment by Algorab** [comment]
That true. As far as I found async-compression and actix uses both flate2

**Comment by chrislearn** [comment]
I created a new version of compression, remove async-compression, this version is non compress branch. @Algorab Can you help to test it?

**Comment by chrislearn** [comment]
Please take a look at the "compress" branch on GitHub, which removed the "async-compression".

I suspect that the performance difference between Salvo and Actix may be due to different compression algorithm settings, such as different compression level. 

You can use the code below to test the performance difference between different algorithms.

```rust
    let router = Router::with_hoop(Logger::new())
        .hoop(Compression::new().enable_gzip(CompressionLevel::Fastest))
        .push(Router::new().path("abc").get(abc))
        .push(Router::new().path("sse").get(sse_stream));
```

Change `CompressionLevel::Fastest` to `CompressionLevel::Minsize`.

**Comment by Algorab** [comment]
I was only able to test today. I saw the compress branch was already merged so I test on the main branch. I can confirm that is now really faster with 620000 messages/s in fasted compressed mode. That is enough. Thank's for the quick response and fix.
