### ISSUE TITLE
Integration with validation library?

### ISSUE THREAD

**Issue by zajimumaaa** [salvo-rs/salvo#275]
**Is your feature request related to a problem? Please describe.**
It's a bit tedious to validate request body and query param and then manually return appropiate error message, it would be nice if there's some kind of integration with validation library that remove boilerplate to validate and return appropiate error message similiar to python web framework like `fastapi` that integrate with `pydantic`.

**Describe the solution you'd like**
Integration with validation library like [`validator`](https://github.com/Keats/validator) or [`garde`](https://github.com/jprochazk/garde). Currently [`garde`](https://github.com/jprochazk/garde) has an integration with `axum` [here](https://github.com/jprochazk/garde/tree/main/integrations/axum_garde) that may be used as reference to integrate [`garde`](https://github.com/jprochazk/garde) to `salvo`

**Describe alternatives you've considered**

**Additional context**

**Comment by chrislearn** [comment]
Duplicate：[#168](https://github.com/salvo-rs/salvo/issues/168)
