### ISSUE TITLE
HTTP3

### ISSUE THREAD

**Issue by liuzonglin1** [salvo-rs/salvo#276]
PS D:\.github\hello-salvo> cargo run
error: failed to parse manifest at `D:\.github\hello-salvo\Cargo.toml`

Caused by:
  error inheriting `salvo` from workspace root manifest's `workspace.dependencies.salvo`

Caused by:
  failed to find a workspace root

**Comment by chrislearn** [comment]
You are not set your project correctly, If you are not using workspace, please remove related settings.
