### ISSUE TITLE
sse-gzip with slow stream

### ISSUE THREAD

**Issue by Algorab** [salvo-rs/salvo#281]
**Description**
On a slow sse stream with gzip no output(message, keep-alive) is written for large period of time. After this time, all messages which are collected at this time are written at once. And then the next wait time starts.

**To Reproduce**
See the demo project [salvo-sse-gzip with slow stream](https://github.com/Algorab/salvo-sse-gzip/tree/slow-stream)

**Expected behavior**
Write for every received sse message / keep-alive a corresponding transfer chunk to the client

**Comment by chrislearn** [comment]
Have you tested use version 0.41.0? Your Cargo.lock is locked to version 0.40.0.

**Comment by Algorab** [comment]
I thought I have used the from git salvo = {git = "https://github.com/salvo-rs/salvo.git", branch = "main", features = ["sse", "logging", "compression"]} which should be the latest. You are right in the lock file is 0.40.0
I will test it against 0.41.0 and check the lock file.

**Comment by Algorab** [comment]
I just do a change to 0.41.0 and tested it. The behavior is the same as described in the first post.

**Comment by chrislearn** [comment]
I fixed it, please try again.

**Comment by Algorab** [comment]
Good morning, yes it is working as expected. Cool :thumbsup: thank's a lot .
