### ISSUE TITLE
Support jwt auth / validation with a issuer url ; .well-known/openid-configuration

### ISSUE THREAD

**Issue by Algorab** [salvo-rs/salvo#282]
**Description**
As far as I can see jwt auth/validation is only supported by a secret key. Very often a  identity and access management tool such as keycloak ( oidc ) is used.

**Describe the solution you'd like**
Support jwt auth / validation with an issuer url btw. .well-known/openid-configuration

**Comment by chrislearn** [comment]
Should it be added as as a feature of jwt_auth, or it should be another middleware?

**Comment by Algorab** [comment]
After thinking a little about it. Personally I would say this an other configuration option for the basic jwt validation (jwt_auth). I see a custom claim validation for example some special requirements, more in a separate middleware. So that there a two step's one for check jwt token exists and is valid and second  custom validation for public and mainly private claims.

**Comment by chrislearn** [comment]
Please see this example:
https://github.com/salvo-rs/salvo/blob/oidc/examples/jwt-oidc-clerk/src/main.rs

Is this feature meet your requirement?
