### ISSUE TITLE
`with_path("<**path>")` should not merge two adjacent `/` into one.

### ISSUE THREAD

**Issue by thep0y** [salvo-rs/salvo#287]
**Describe the bug**
`with_path("<**path>")` merges two adjacent `/` into one.

**To Reproduce**
```rust
fn main() {
    // ...
    let router = Router::new()
        .push(Router::with_path("<**path>").get(handle);
    // ...
}

#[handler]
fn handle(req: &mut Request) {
    let path = req.param::<String>("**path").unwrap();
    println!("{path}");
}
```

Visit: `/https://example.com`

Output:
```
https:/example.com
```

The expected output result is:
```
https://example.com
```

**Comment by chrislearn** [comment]
This looks not a valid url path.

**Comment by thep0y** [comment]
> This looks not a valid url path.

It is indeed not a valid path, but `**path` should not modify it, right?

**Comment by chrislearn** [comment]
Path like 'a//b' is normalized to 'a/b' in salvo. This is way this path is changed.

**Comment by thep0y** [comment]
> Path like 'a//b' is normalized to 'a/b' in salvo. This is way this path is changed.

I haven't used any other Rust web frameworks, and popular web frameworks in other languages such as Go and Python don't handle // as / in the same way.

**Comment by chrislearn** [comment]
Is there any situation we must remain '//'? In most case it just typo.

**Comment by thep0y** [comment]
To set a proxy in `gitconfig`:

```
[url "https://example.com/https://github.com"]
        insteadOf = https://github.com
```

Replacing `//` with `/` is unexpected, and the URL needs to be restored to `//` in order to be valid.

**Comment by chrislearn** [comment]
you should encoded https://github.com.

**Comment by chrislearn** [comment]
[url "https://example.com/https%3A%2F%2Fgithub.com"]
