### ISSUE TITLE
How to handle 404/40X errors?

### ISSUE THREAD

**Issue by biluohc** [salvo-rs/salvo#29]
当前路由不匹配的，会返回一个默认的html页面，这对api服务是比较奇怪的, 根路由配置一个after来抓404貌似不行？

像actix-web的话，允许用户分别配置一个处理404，json表单解析错误之类的Fn

**Comment by driftluo** [comment]
404 will be caught by this implementation: https://docs.rs/salvo/0.11.2/salvo/struct.CatcherImpl.html

If you don’t need to return to the default 404 page, you can implement one yourself, and then set it through this API: https://docs.rs/salvo/0.11.2/salvo/struct.Service.html#method.catchers

**Comment by biluohc** [comment]
Response 的 http_error 这个字段私有，没有method能访问它，这个有办法解决吗？

```
pub struct CatcherImpl(HttpError);
impl CatcherImpl {
    pub fn new(e: HttpError) -> CatcherImpl {
        CatcherImpl(e)
    }
}
impl Catcher for CatcherImpl {
    fn catch(&self, req: &Request, res: &mut Response) -> bool {
        let status = res.status_code().unwrap_or(StatusCode::NOT_FOUND);
        if status != self.0.code {
            return false;
        }
        let format = guess_accept_mime(req, None);
        let err = if res.http_error.is_some() {
            res.http_error.as_ref().unwrap()
        } else {
            &self.0
        };
        let (format, data) = err.as_bytes(&format);
        res.headers_mut()
            .insert(header::CONTENT_TYPE, format.to_string().parse().unwrap());
        res.write_body_bytes(&data);
        true
    }
}
```

**Comment by driftluo** [comment]
Custom 404 returns do not need to access this field, it is empty by default, why do you need to access this field?

**Comment by biluohc** [comment]
看起来里面有更详细的错误信息，，不行就算了

**Comment by driftluo** [comment]
There are two sources of the `http_error`:
1. Manually set by the user, use https://docs.rs/salvo/0.11.2/salvo/struct.Response.html#method.set_http_error
2. The user forces the framework to be set, use `render_json` with no serde data

In the case of 404, this will always be empty

By the way, the real scene of the `Catcher` is to customize the HTTP code of 400 -600 to customize the return value, which is the built-in default page by default.

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/blob/master/core/src/http/errors/http_error.rs
这个里面提供了默认的错误信息, 它会根据请求需要的格式自动匹配发送 html, xml, 或者 json 的格式的错误.

然后刚刚我对代码作了点改进, @biluohc 你可以使用 0.11.4 的版本试一下.
我也添加了新的示例, 你可以看一下:  https://github.com/salvo-rs/salvo/blob/master/examples/custom_error_page.rs
示例中只是添加了一个只捕获404错误的页面, 如果是其他错误, 依然调默认的错误处理实现.
@biluohc 你看现在这样是不是能更好地满足你的需求.

**Comment by chrislearn** [comment]
> 
> 
> 看起来里面有更详细的错误信息，否则只能看到一个状态码，不行就算了

对于你说的这个更详细的错误, 其实简单地从状态码构建的默认的错误信息而已.
```
macro_rules! default_catchers {
    ($($code:expr),+) => (
        let list: Vec<Box<dyn Catcher>> = vec![
        $(
            Box::new(CatcherImpl::new($crate::http::errors::http_error::from_code($code).unwrap())),
        )+];
        list
    )
}

```

**Comment by biluohc** [comment]
https://github.com/salvo-rs/salvo/blob/master/extra/src/serve/dir.rs#L18

这个结构得在上级 pub use 出来吧，这样的没有完全导出只能用Default生成使用，但是一改它字段再使用，rust就会告诉类型未知了。。

**Comment by biluohc** [comment]
还有就是compress模块，你们测试过吗，一访问就卡住没有返回了，应该不是macos的问题

**Comment by chrislearn** [comment]
> https://github.com/salvo-rs/salvo/blob/master/extra/src/serve/dir.rs#L18
> 
> 这个结构得在上级 pub use 出来吧，这样的没有完全导出只能用Default生成使用，但是一改它字段再使用，rust就会告诉类型未知了。。
> 

这种问题你可以直接上PR哈。

**Comment by biluohc** [comment]
关于根路由的after handler运行的时机？

我准备写个日志中间件，结果发现部分请求到达这个中间件的时候status_code是None(StaticDir的顶级目录状态码空，子文件又是200)。还有就是404之类的请求并不会进入这个after（这个逻辑上倒是没问题）

**Comment by driftluo** [comment]
> StaticDir的顶级目录状态码空，子文件又是200

Access directory under `listing` mode, it seems that HTTP code is not set, I have not used this mode. So I didn't encounter this problem, is this the problem?

**Comment by driftluo** [comment]
> 关于根路由的after handler运行的时机？

After handle execution conditions:
1. The routing has matching
2. When the execution of before/path handle is completed, that is, after response commit, all after is executed in order

**Comment by biluohc** [comment]
我觉得吧，Response new的默认状态码应该是200吧？否则就和打地鼠一样，到处都要设置200，到处都忘记。不过这样做会和框架本身冲突吗？

**Comment by driftluo** [comment]
> 我觉得吧，Response new的默认状态码应该是200吧？否则就和打地鼠一样，到处都要设置200，到处都忘记。不过这样做会和框架本身冲突吗？

Yes, if there is no HTTP code, it means that salvo needs to continue to execute before/path handle until it is completed or there is no more handle. 

Salvo does not use Error as a sign to suspend execution, and the Response's ownership is not in the hands of the user, this is also one of the costs.

**Comment by biluohc** [comment]
或者这样，如果状态码不空就 render_json/binary 之类的函数填一个200，用户可以在render前设置，也可以在后面覆盖掉

**Comment by driftluo** [comment]
> 或者这样，如果状态码空就 render_json/binary 之类的函数填一个200，用户可以在render前设置，也可以在后面覆盖掉

I changed it to 200 by default, it seems there is no problem, wait for review @chrislearn

**Comment by biluohc** [comment]
```
render_json/binary 之类的函数如果发现状态码空就填一个200，这样用户可以在render前设置，也可以在后面覆盖掉
    This is still wrong, I can’t default to 200, I need to go back
```
这样会有什么样的副作用？？

**Comment by chrislearn** [comment]
默认情况下不需要添加状态码. 也就是None.
如果一切OK, 最后写入到 Hyper 的 Response 时会自动添加状态码 200.
如果过程中有错误, 可以手工设置状态码. 比如在 Middleware 里面出现了错误等.

有什么情况是需要提前设置状态码的呢?
