### ISSUE TITLE
Proposal to switch from h3 to sec-http3 for webtransport

### ISSUE THREAD

**Issue by darioalessandro** [salvo-rs/salvo#303]
Hey @chrislearn !! 

We want to invite you consider from h3 to sec-http3 so that you can help us to shape up the library. 

We would like you to invite you to become a maintainer along with @ten3roberts. 

What do you think?

**Comment by chrislearn** [comment]
Thank you for your suggestion, but for the sake of convenience in making modifications, I have temporarily forked h3. In the future, I will still switch back to using h3.

**Comment by darioalessandro** [comment]
sounds good, sec-http3 is a fork of h3 that is more actively maintained, let us know if you change your mind
