### ISSUE TITLE
logging middleware: res.status_code is empty

### ISSUE THREAD

**Issue by wonktondI** [salvo-rs/salvo#305]
![image](https://github.com/salvo-rs/salvo/assets/41692176/3eef00cd-14b0-443a-9894-3d360733d8ff)

日志中间件中，res.status_code 是 None。不能正常返回 code

**Comment by chrislearn** [comment]
默认情况下 response 确实 status_code = None;
如果你设置过 status_code, 或者有 res.render(StatusError) 则这里的 status_code 应该就不是 None 了.

**Comment by infdahai** [comment]
这里要返回个默认值吗？

**Comment by chrislearn** [comment]
默认值就是none.没啥意义，所以大概做了个判断。

**Comment by wonktondI** [comment]
![image](https://github.com/salvo-rs/salvo/assets/41692176/6fe93bfe-d5bb-4409-b291-3367654fa0ed)
![Uploading image.png…]()
在 handler 返回时，**res.status_code(StatusCode::CREATED)  (or StatusCode::OK );**，可以在中间件中获取到 status_code了。
在返回成功时，能默认给一个 **res.status_code(StatusCode::OK)** 吗？

**Comment by chrislearn** [comment]
做了一点修改, 其实现在的 `None` 就当作 `StatusCode::OK`.  不过我仍然想明确区分用户有没有显式设置状态码. 所以, 这里的 `status_code` 类型是 `Option<StatusCode>`.

**Comment by infdahai** [comment]
嗯。我觉得这样会好点。

**Comment by wonktondI** [comment]
在 handler 里， res.render() 这个方法里，返回成功时，设置一下状态码，这样可行吗？

**Comment by chrislearn** [comment]
状态码是会设置的，只是是在所有的handler执行完毕。而log中间件也是handler 所以设置晚于这个handler的执行。

**Comment by wonktondI** [comment]
明白了🌹
