### ISSUE TITLE
endpoint macro  compiling error. When there is a crate named core, the endpoint macro results in an error.

### ISSUE THREAD

**Issue by fankaiLiu** [salvo-rs/salvo#306]
**Describe the bug**
as per the title

**To Reproduce**
[here is demo](https://github.com/fankaiLiu/salvo_issue_demo)

**Expected behavior**
Compile normally

**Desktop (please complete the following information):**
 - OS: [mac]
 - Version [0.44]

**Additional context**
I wonder which duplicate name of the upstream crate library is CORE and not fully qualified?

**Comment by chrislearn** [comment]
https://github.com/dtolnay/async-trait/issues/109
