### ISSUE TITLE
requires tracing-subscriber = "*" in toml dependencies

### ISSUE THREAD

**Issue by lineality** [salvo-rs/salvo#308]
**Describe the bug**
"error[E0433]: failed to resolve: use of undeclared crate or module `tracing_subscriber` "
at least on fedora, running getting started code from website requires tracing-subscriber = "*" in toml dependencies

**To Reproduce**
follow your website: https://salvo.rs/book/guide.html (at least on fedora 38)

**Expected behavior**
This (program runs correctly) happens IF toml is updated: $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/hello_salvo`
2023-07-04T19:02:40.165698Z  INFO salvo_core::server: listening HTTP/1.1 on http://127.0.0.1:5800

**Screenshots**

**Desktop (please complete the following information):**
 - OS: fedora 38 (rpm linux)
 - Browser [not relevant, error in terminal]
 - Version [of what?]

**Additional context**
to fix problem, use this for Cargo.toml:

[package]
name = "hello_salvo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = "*"
tokio = { version = "1", features = ["macros"] }
tracing-subscriber = "*"

**Comment by chrislearn** [comment]
This is a document issue and I fixed, thanks!
