### ISSUE TITLE
can not build without openssl with feature jwt-auth enabled

### ISSUE THREAD

**Issue by diablur** [salvo-rs/salvo#330]
jwt-auth depends on reqwest which depends on native-tls by default,
so i can't build only enable rustls feature

**Comment by diablur** [comment]
https://github.com/diablur/salvo-test.git
run docker build -t test:latest .

**Comment by chrislearn** [comment]
Is it same as https://github.com/salvo-rs/salvo/issues/313

**Comment by diablur** [comment]
i'm using 0.48,but the same problem
base image alpine have no openssl installed,
so build fail

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/issues/313#issuecomment-1629114263

**Comment by diablur** [comment]
it doesn't work.i don't want to link openssl

reqwest has a default feature ["default-tls"]
![WeChat5d2da91bfc5cdf1f052d07c6bf4def6b](https://github.com/salvo-rs/salvo/assets/11729720/8cdf412c-f1ae-48d0-80e0-b94163626c0b)

maybe we should add rustls-tls feature to reqwest beside "json" in jwt-auth crate?

**Comment by chrislearn** [comment]
have you tried? jwt-auth will not include  reqwest if feature oidc is disabled.

If you enable crate salvo's feature jwt-auth, the crate salvo - jwt-auth  will include with feature 'all'. 

But if you disable feature 'jwt-auth' in 'salvo' and include 'salvo-jwt-auth' individual, it will use default feature without 'oidc'.

**Comment by diablur** [comment]
i mean whether jwt-auth should support rustls with oidc enabled?

**Comment by chrislearn** [comment]
I am not sure why reqwest default use openssl not rustls. But I perfer just use reqwest's default feature.

**Comment by prabirshrestha** [comment]
Hit into this again. Would be great if openssl is optional. Primary reason for this is it makes building hard as one needs c compilers or openssl installed. Would be great if this was fixed.
