### ISSUE TITLE
hello-h3的http3功能不能正常使用

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#331]
通过浏览器无法正常访问，如果用curl进行访问会显示`curl: (56) Recv failure: Connection reset by peer`

火狐访问，日志会显示
> 2023-07-20T03:52:36.147817Z ERROR salvo_core::server: accept connection failed error=Custom { kind: Other, error: "received fatal alert: UnknownCA" }

chrome访问，日志
>2023-07-20T03:53:25.123210Z ERROR salvo_core::server: accept connection failed error=Custom { kind: Other, error: "received fatal alert: CertificateUnknown" }

如果使用mkcert生成的证书，直接无法响应

**Comment by chrislearn** [comment]
已经修复。 version 0.48.2
