### ISSUE TITLE
Static serve example does not work

### ISSUE THREAD

**Issue by FallingSnow** [salvo-rs/salvo#333]
**Describe the bug**
Static serve example results in only 404s.

**To Reproduce**
1. Clone main branch
2. Run `static-dir-list` example
3. See only 404s (`http://localhost:5800/boy/play.html`)

**Comment by FallingSnow** [comment]
Hardcoding the full path seems to resolved the issue.

**Comment by chrislearn** [comment]
Use this paths:

```rust
        StaticDir::new([
            "static-dir-list/static/boy",
            "static-dir-list/static/girl",
        ])
```

**Comment by FallingSnow** [comment]
Pulled the latest commit. It still is not working for me. Shouldn't paths like `http://localhost:5800/sleep.txt` work?

I also found that hardcoding the full path only works to pull up `index.html`, nothing else.

**Comment by chrislearn** [comment]
How do you run the example? You should:

```bash
cd examples
cargo run -p example-static-dir-list
```

**Comment by FallingSnow** [comment]
Okay, that works. I was running them with:
```sh
cd examples/static-dir-list
cargo run
```

Thank you!
