### ISSUE TITLE
Websocket upgrade in proxy crate not working

### ISSUE THREAD

**Issue by lostb1t** [salvo-rs/salvo#337]
When I try to proxy a web socket connection with the proxy example iI always get: 'response does not have an upgrade extension'

Tracing it a bit down in the proxy crate:

```                
let response_upgraded = response
                    .extensions_mut()
                    .remove::<OnUpgrade>()
                    .ok_or_else(|| Error::other("response does not have an upgrade extension"))?
                    .await?;
```
Never returns an upgrade. OnUpgrade never exists in the extensions.

If replace it with `let mut response_upgraded = response.upgrade().await.unwrap();` it works fine. (consumes the response tho)

**Comment by chrislearn** [comment]
Fixed in version 0.49.1
