### ISSUE TITLE
Serve compressed static assets if available

### ISSUE THREAD

**Issue by FallingSnow** [salvo-rs/salvo#350]
**Is your feature request related to a problem? Please describe.**
I build a SPA web application with gzip compressed files in addition to the regular files. When using the `StaticDir` middleware, salvo does not automatically serve that asset. For example if I have a file `main.bundle.js.gz` and a client requests `main.bundle.js` with the header `Accept-Encoding: gzip`, salvo should return the `main.bundle.js.gz` file with the `Content-Encoding: gzip` header.

**Describe the solution you'd like**
I believe it would be best to integrate a solution into the static middleware. The static middleware should query all the files in the supplied root directory and build a map of files with `.gz` extensions. Then provide those files when a client requests a matching non `.gz` ending file.

**Describe alternatives you've considered**
The compression middleware exists but only provides single shot runtime compression.

It may be possible to achieve a result where compression only occurs once (on first load) by using the compression, cache, and static middlewares together but I haven't looked into that.

**Additional context**
If this is implemented in the static middleware it might be best to expose a public rescan method.

**Comment by chrislearn** [comment]
I think this may cause major confusion. For example, when there are two files index.css and index.css.gz. So far, I haven't seen any framework do this.

**Comment by FallingSnow** [comment]
That is true, although I do think it's relatively reasonable to expect `index.css.gz` to be `index.css` but gziped.

Either way I think making this behavior (serve `index.css.gz` for a `index.css.gz` request) should be opt-in by default to prevent any possible unexpected behavior.

[Here](https://www.npmjs.com/package/express-static-gzip) is an example of an addition for the express framework.

As a side note; I tried changing my requests to `.gz` but then the static middleware returns a content type for gzip and not a content encoding. But this is expected behavior.

**Comment by chrislearn** [comment]
Perhaps such a function is required under certain circumstances, but it is recommended to implement it through middleware, which should not be difficult.
1. Check `req.params("**rest")`, add .gz suffix to it.
2. Modify the content_type header information after `ctrl.call_next()`.

**Comment by FallingSnow** [comment]
Got it working. Here is the *unrefined* code for anyone else that needs this.
```rust
#[handler]
async fn serve_precompressed(
    &self,
    req: &mut Request,
    depot: &mut Depot,
    res: &mut Response,
    ctrl: &mut FlowCtrl,
) {
    let path = req.uri().path();
    if path.ends_with(".js") {
        
        let params = req.params_mut();
        params.get_mut("**path").unwrap().push_str(".gz");

        ctrl.call_next(req, depot, res).await;
        if ctrl.is_ceased() {
            return;
        }
        res.add_header("Content-Type", "text/javascript", true).expect("Unable to set Content-Type header");
        res.add_header("Content-Encoding", "gzip", true).expect("Unable to set Content-Encoding header");
    }
}
```

Use it with `.hoop(serve_precompressed)`.

Thanks @chrislearn for pointing me in the right direction!

**Comment by chrislearn** [comment]
Done
