### ISSUE TITLE
Typed routes

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#351]
Is it possible to support typed routes so we get compilation error when we pass wrong params or invalid urls.

Saw that dioxus uses enums for strongly typed router. https://dioxuslabs.com/blog/release-040 and https://dioxuslabs.com/learn/0.4/migration/router

I'm probably spoiled due to https://tanstack.com/router/v1 on the typescript side.

**Comment by chrislearn** [comment]
I don't quite understand what a "typed router" is. If salvo implements such a function, what will it look like? Can you provide pseudocode to see?
