### ISSUE TITLE
Working with tower example broken

### ISSUE THREAD

**Issue by lostb1t** [salvo-rs/salvo#358]
```
error: failed to parse manifest at `/Users/sarendsen/Projects/salvo/examples/work-with-tower/Cargo.toml`

Caused by:
  error inheriting `salvo` from workspace root manifest's `workspace.dependencies.salvo`

Caused by:
  `dependency.salvo` was not found in `workspace.dependencies`
```

**Comment by chrislearn** [comment]
This example can not working correctly in current version, so it is excluded in workspace Cargo.toml

**Comment by chrislearn** [comment]
I added a concurrency limiter middleware.
Example: https://github.com/salvo-rs/salvo/blob/main/examples/concurrency-limiter/src/main.rs

**Comment by chrislearn** [comment]
Have you tested my `concurrency-limiter`? It should not drop the request.
