### ISSUE TITLE
Cache panics with error handling

### ISSUE THREAD

**Issue by sarendsen** [salvo-rs/salvo#365]
```rust

Router::new()
                .path(".test)
                .hoop(default_cache())
                .get(test),
        )

#[handler]
pub async fn test(
    req: &mut Request,
    res: &mut Response,
) -> Result<(), salvo::Error> {
 Err(salvo::http::StatusError::internal_server_error().into())
}

```

Results in panic:

```thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Other("unsupported body type"), /Users/sarendsen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salvo-cache-0.50.3/src/lib.rs:288:67```

**Comment by chrislearn** [comment]
Fixed in version 0.50.5
