### ISSUE TITLE
About proxy: Is not working

### ISSUE THREAD

**Issue by josejachuf** [salvo-rs/salvo#368]
**Describe the bug**
I have tried it for a long time and worked fine, but now it doesn't work

**To Reproduce**
The example "proxy-simple"

depending on the site to which the problems are accessed are different

**Expected behavior**

**Screenshots**

http://127.0.0.1:5800/google

GET
http://127.0.0.1:5800/google
[HTTP/1.1 400 Bad Request 147ms]

![imagen](https://github.com/salvo-rs/salvo/assets/5981345/9594ad7c-b397-43ac-8364-20628db0b571)

http://127.0.0.1:5800/rust

Content Security Policy: La configuración de la página bloqueó la carga de un recurso en eval ("default-src").
Source: ;(function r(e,t=!1){const o="6.0";let i… rust

![imagen](https://github.com/salvo-rs/salvo/assets/5981345/64849959-38c0-4e9a-ad26-42fa1c2d5af4)

http://127.0.0.1:5800/salvo

![imagen](https://github.com/salvo-rs/salvo/assets/5981345/b75efb49-cf00-4768-a74a-46ee60d742f9)

I saw that the repository had many changes in recent days in relation to the proxy feature

**Comment by chrislearn** [comment]
This is not bug, just google treat request is illegal, and rust website has path issue.
I updated the example, google removed, you can check it again.

**Comment by chrislearn** [comment]
Please see this issue: https://github.com/salvo-rs/salvo/discussions/363
