### ISSUE TITLE
请添加RUTLS可以使用自己实现的ResolvesServerCert trait类

### ISSUE THREAD

**Issue by luluxiuxiu** [salvo-rs/salvo#374]
**Is your feature request related to a problem? Please describe.**
请添加RUTLS可以使用自己实现的ResolvesServerCert trait类，当我们需要动态证书的时候，可以通过实现ResolvesServerCert trait来完成自己自定义解析，但是目前salvo不具备该功能。

**Describe the solution you'd like**
可以在rustlsconfig中对于fallback或者是其他变量增加针对 ResolvesServerCert trait 实现类的定义，或者在其他地方增加一个可以传入并使用自己ResolvesServerCert trait实现类的地方

**Describe alternatives you've considered**
我目前没有什么更好的替代方案，我们尝试实现自己的Listner以便解决这个问题

**Additional context**

**Comment by chrislearn** [comment]
直接允许 ServerConfig 作为配置， 应该能解决你的问题吧？
