### ISSUE TITLE
Add support for sending tokio::io::AsyncSeek for range requests

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#385]
I'm looking to enable simple native mp4 video playback via browsers and can't seem to get it working when using streams. Streams doesn't seem to support range requests since it isn't seeakble. I'm using [opendal](https://opendal.apache.org/) so I can support multiple backends such as S3/SMB/filesystem. Is it possible to support sending range requests for [tokio::io::AsyncSeek](https://docs.rs/tokio/latest/tokio/io/trait.AsyncSeek.html) used by [opendal::Reader](https://docs.rs/opendal/latest/opendal/struct.Reader.html).

<details>

<summary>Code</summary>

You can download a sample mp4 video from https://test-videos.co.uk/bigbuckbunny/mp4-h264 and add rename it to video.mp4.

```toml
[dependencies]
salvo = "0.51.0"
tokio = { version = "1", features = ["macros"] }
tokio-util = { version = "0.7.8", features = ["io"] }
tracing = "0.1"
tracing-subscriber = "0.3"
```

```rust
use salvo::{fs::NamedFile, prelude::*};
use tokio_util::io::ReaderStream;
use tracing::debug;

#[handler]
async fn index(res: &mut Response) {
    res.render(Text::Html(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
	<title>Video Player</title>
</head>
<body>
    <h2>/video.mp4</h2>
	<video loop controls='true' width='200px' height='200px' src='/video.mp4' type='video/mp4'></video>
    <h2>/video_stream.mp4</h2>
	<video loop controls='true' width='200px' height='200px' src='/video_stream.mp4' type='video/mp4'></video>
</body>
</html>"#,
    ));
}

#[handler]
async fn video(req: &mut Request, res: &mut Response) {
    NamedFile::builder("video.mp4")
        .send(req.headers(), res)
        .await;
}

#[handler]
async fn video_stream(res: &mut Response) {
    let file = tokio::fs::File::open("Cargo.toml").await.unwrap();
    let stream = ReaderStream::new(file);
    res.add_header("Content-Type", "video/mp4", true).unwrap();
    res.streaming(stream).unwrap();
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().init();

    let router = Router::new()
        .get(index)
        .push(Router::new().path("/video.mp4").get(video))
        .push(Router::new().path("/video_stream.mp4").get(video_stream));
    let acceptor = TcpListener::new("0.0.0.0:4000").bind().await;
    Server::new(acceptor).serve(router).await;
}
```

</details>

`/video.mp4` is using `NamedFile` so range requests works. `/video_stream.mp4` uses streaming and it doesn't work since range request is not supported.

![image](https://github.com/salvo-rs/salvo/assets/287744/2aae2681-fc46-487d-9513-2290bdbcea83)

An api similar to the following pseudo code would be great.

```
if req has "range" header {
   let async_seekable: tokio::io::AsyncSeek = ...;
   res.send_seekable(req, async_seekable);
else {
   let stream = ....;
   res.streaming(stream);
}
```

Here is a [blog post](https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/) that goes more into playing mp4 videos natively in browser using range requests.

**Comment by chrislearn** [comment]
AsyncSeek does not give content length information, how to set response header `Content-Length`?

**Comment by prabirshrestha** [comment]
It is a bummer that it doesn't support `Content-Length` though it makes sense why. What about passing explicit content-length?


```rust
let content_length = ...;
let seekable = ....;
res.send_seekable(req, seekable, content_length);
```

**Comment by prabirshrestha** [comment]
Tested directly from main branch and it works. Thanks for the quick fix!

Waiting for the new release so I can start using this `ReadSeeker` feature for salvo!
