### ISSUE TITLE
salvo_oapi::ToSchema OOTB support for Result<T, E>

### ISSUE THREAD

**Issue by Roba1993** [salvo-rs/salvo#427]
**Is your feature request related to a problem? Please describe.**
The `ToSchema` derive is not supporting rust standard results like `Result<String, String>`.

**Describe the solution you'd like**
Generic results should be supported, when both internal types also support `ToSchema`.

**Describe alternatives you've considered**
Manually implement a own `Result` enum which services `ToSchema`.

**Comment by chrislearn** [comment]
I'm not sure about this. Can you give me a specific scenario where you need to implement this?

**Comment by Roba1993** [comment]
Yes for sure. I have the following struct:
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceResult {
    pub start_time: DateTime,
    pub duration: Duration,
    pub fn_output: Result<Vec<Value>, String>,
    pub log: String,
}
```

The variable `fn_ouput` either returns a list of values returned from a script run on the server or an String error message.
