### ISSUE TITLE
Add support for hyper::body::Sender equivalent in salvo

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#444]
I'm working on HLS streaming and it is expensive to spawn ffmpeg and pipe the stdout to the response body so looking into doing that in a background thread. hyper supports [hyper::body::Sender](https://docs.rs/hyper/latest/hyper/body/struct.Sender.html). Would be great if there is an equivalent of this api exposed in salvo.

```rust
#[handler]
async fn hello() -> Result<()> {
  let (mut sender,body)=hyper::body::Body::channel();

  tokio::spawn(async move { // or   std::thread::spawn(move || { ... })
    // Command::new() ... and send stdout to sender.
    sender.send_data(some_bytes).await?;
  });

  res.render(body)
  Ok(())
}
```

Or is this somehow already possible with streaming?

**Comment by depth-liu** [comment]
https://github.com/salvo-rs/salvo/blob/channel/examples/body-channel/src/main.rs
