### ISSUE TITLE
cannot use tokio::io::copy in v0.57.0

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#446]
Following code no longer works in v0.57.0

```rust
let mut file = async_compat::Compat::new(writer);
let mut src = StreamReader::new(req.take_body());
tokio::io::copy(&mut src, &mut file).await.unwrap();
```

```
tokio::io::copy(&mut src, &mut file).await....
    |     --------------- ^^^^^^^^ the trait `Buf` is not implemented for `Frame<hyper::body::Bytes>`
```

I need this to compute the sha-1 hash for the request body so I can validate the upload has completed successfully.

```rust
let mut src = HashRead::new(StreamReader::new(req.take_body()));
```

**Comment by chrislearn** [comment]
This is not bug.

**Comment by chrislearn** [comment]
Maybe you need to convert body:
```rust
let body = body.map(|f| f.map(|f| f.into_data().unwrap_or_default()));
```

**Comment by prabirshrestha** [comment]
`body` isn't an iterator. Am I missing something here?

```rust
#[handler]
async fn hello(req: &mut Request, res: &mut Response) -> Result<()> {
    let body = req.take_body();
    let body = body.map(|f| f.map(|f| f.into_data().unwrap_or_default()));
    let mut src = StreamReader::new(body);
    Ok(())
}
```

**Comment by chrislearn** [comment]
> `body` isn't an iterator. Am I missing something here?
> 
> ```rust
> #[handler]
> async fn hello(req: &mut Request, res: &mut Response) -> Result<()> {
>     let body = req.take_body();
>     let body = body.map(|f| f.map(|f| f.into_data().unwrap_or_default()));
>     let mut src = StreamReader::new(body);
>     Ok(())
> }
> ```

I tested your code and it can compile correctly.

**Comment by prabirshrestha** [comment]
It works. Thanks.
