### ISSUE TITLE
Get AsyncWrite for response

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#451]
I'm looking into zipping a file or directories on the fly and would like to get the `AsyncWrite` for the ResponseBody.

```rust
let res_body = res.take_body();
let mut writer = ...get writer from res body...
let mut zip_writer = async_zip::tokio::write::ZipFileWriter::with_tokio(writer);
// do something with zip_writer
```

https://docs.rs/async_zip/latest/async_zip/base/write/struct.ZipFileWriter.html

Same goes for create tar archives which needs AsyncWrite. https://docs.rs/tokio-tar/0.3.1/tokio_tar/struct.Builder.html

Is there a way to get AsyncWrite easily so we can write it to response easily with these libraries?

**Comment by chrislearn** [comment]
You need to use type to convert it to stream. for example:
https://docs.rs/tokio/latest/tokio/io/fn.duplex.html

**Comment by chrislearn** [comment]
You can use `res.channel()` get a `sender`, It impl `AsyncWrite` now.

**Comment by prabirshrestha** [comment]
This works. Thanks for the quick fix.

I was using duplex but found that having a AsyncWrite supported by default would be better.
