### ISSUE TITLE
Tower layer compat 404 not found and `TowerServiceCompat`  bounds too restrictive

### ISSUE THREAD

**Issue by Totodore** [salvo-rs/salvo#468]
**Describe the bug**
* My tower layer with `compat` is never called (the server always return a 404 request on /engine.io with the default html page, the service is never called)
* The `TowerServiceCompat` bounds requires an inner service with `hyper::Request<ReqBody>` and ReqBody is not generic (it is an internal type in salvo, therefore it is impossible to use `TowerServiceCompat` from outside of the lib). Maybe we could release this bound, either by using `hyper::Incoming` type, or even better : `http_body::Body` type.

**To Reproduce**
* `git clone https://github.com/Totodore/socketioxide --branch chore(deps)-hyper-1.0`
* Start the example: cargo run --bin salvo-echo
* Make a request on `http://127.0.0.1:3000/engine.io`
* Here is the link to the tower and hyper 1.0 service implementation: [engineioxide/src/service/hyper_service.rs](https://github.com/Totodore/socketioxide/blob/chore(deps)-hyper-1.0/engineioxide/src/service/hyper_service.rs)

**Expected behavior**
* I should be able to get a response code != 404 when making GET requests on `http://127.0.0.1:3000/engine.io`
* I should be able to call `.compat()` on a tower service with `hyper::Request<Incoming>` or `hyper::Request<impl http_body::Body>` bound. The solution might be to change the bound to `hyper::Request<Into<ReqBody>>` if `ReqBody` implements `From<Incoming>` for example.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 0.58.2

**Additional context**
It is more a feature request but the add of a `compat()` trait for any `hyper::Service` would help me a lot because it does not exist with `hyper 0.4`. Therefore it would be possible have the two differrent implementation for hyper v0.4 and v1 at the same time. 
I would be able to provide backward compatibility when enabling the feature `hyper-1.0` for my [`socket.io`](https://github.com/Totodore/socketioxide) lib. Also it would make the feature `hyper-1.0` only additive.

**Comment by chrislearn** [comment]
```rust
Router::with_path("<**path>").hoop(layer).get(hello);
```
This router only match path "/". You can try to use this Router config:

```rust
Router::with_path("<**path>").hoop(layer).get(hello);
```

**Comment by Totodore** [comment]
Thank you for your response, I should have read the docs correctly

**Comment by Totodore** [comment]
For the second point, are you considering making a PR to release the Service trait bound ? Or is there any alternative solution ?

**Comment by chrislearn** [comment]
> For the second point, are you considering making a PR to release the Service trait bound ? Or is there any alternative solution ?

Can you check branch `tower-compat` branch. I am not sure it can work correctly.
