### ISSUE TITLE
Update to Hyper 1.0

### ISSUE THREAD

**Issue by chrislearn** [salvo-rs/salvo#494]

**Comment by chrislearn** [comment]
https://github.com/seanmonstar/reqwest/issues/2039

**Comment by tsingson** [comment]
wait for  update to hyper 1

**Comment by chrislearn** [comment]
> Do you have a date for this upgrade ? It is currently blocking my migration to stable hyper for https://github.com/totodore/socketioxide And because Axum already migrated I now have compat issues with other frameworks

I am waiting reqwest upgrade to hyper 1.0.

**Comment by chrislearn** [comment]
Done!!!
