### ISSUE TITLE
当解析JSON时, 如果JSON为空,则会出现错误. 

### ISSUE THREAD

**Issue by licheng1013** [salvo-rs/salvo#497]
JSON 为空出现了解析错误. 

https://github.com/salvo-rs/salvo/assets/46236080/c48ac8d0-893b-43e4-b83f-8855f0275c08

这里是需要开发者手动处理JSON为空的情况么 ?  

```rs
#[handler]
async fn login(_req: &mut Request, res: &mut Response) {
    let model: Admin = _req.parse_json().await.unwrap();
    logic::admin_logic::login(model).await;
    res.render(Json(ok_msg("插入成功!".to_string())));
}

```

**Comment by chrislearn** [comment]
你这里 `let model: Admin` 如果不提供数据，应该就是返回错误。 或许你可以试试 `let model: Option<Admin>`.

**Comment by licheng1013** [comment]
> 你这里 `let model: Admin` 如果不提供数据，应该就是返回错误。 或许你可以试试 `let model: Option<Admin>`.

好的
