### ISSUE TITLE
StaticDir support filter

### ISSUE THREAD

**Issue by ahaoboy** [salvo-rs/salvo#508]
**Is your feature request related to a problem? Please describe.**
I don't want to display certain files in the folder, such as .git, node_modules, etc.

**Describe the solution you'd like**
```
StaticDir::new([
  "./",
])
.filter( [".git", "node_modules"] )
.defaults("index.html")
.listing(true),
```
**Describe alternatives you've considered**
```
.glob( ["!.git", "!node_modules"] )
```

 ```
.include( [*.js] )
.exclude([".git", "node_modules"])
```

**Comment by chrislearn** [comment]
Added `exclude_filter`.
