### ISSUE TITLE
关于 Extractible 数据提取器，default_source(from = "body"),default_source(from = "body", format = "json"),不能同时存在一个 结构体上的优化

### ISSUE THREAD

**Issue by lo-ferris** [salvo-rs/salvo#517]
![WechatIMG36068](https://github.com/salvo-rs/salvo/assets/118798799/f56e75d9-0810-4f42-818c-79b7fdab801d)

如图所示: 
default_source(from = "body"), default_source(from = "body", format = "json"), 作用在 GoodMan 这个结构体上时，则只能将 Request Payload 解析成 application/x-www-form-urlencoded 格式或者 multipart/form-data 格式 的 form 数据，而不能解析成 application/json

也就是说 default_source(from = "body"), default_source(from = "body", format = "json") 作用在 同一个结构体上时，只有一个生效。

我希望最后优化成 default_source(from = "body") 能 将 Request Payload 解析成包括 form 、json 在内的任意 数据格式。

**Comment by chrislearn** [comment]
completed via #521
