### ISSUE TITLE
Protect Endpoints for Salvo

### ISSUE THREAD

**Issue by shujaatak** [salvo-rs/salvo#525]
Salvo is a fantastic framework and I am wondering if there is something like https://github.com/DDtKey/protect-endpoints for Salvo?

**Comment by chrislearn** [comment]
I don't know about this library, if you need to protect some api, you can add middleware on the router.

```rust
   Router::new("api")
        .push(Router::with_path("admin").hoop(auth_admin).goal(admin))
        .push(Router::with_path("client").hoop(auth_client).goal(client));
```

**Comment by DDtKey** [comment]
For anyone interested: https://github.com/DDtKey/protect-endpoints now supports `salvo` 🎉
