### ISSUE TITLE
OpenApi: Unable to set global Authentication.

### ISSUE THREAD

**Issue by z91300** [salvo-rs/salvo#543]
## 期望:
能全局设置Authentication参数，如下界面
![image](https://github.com/salvo-rs/salvo/assets/73412370/9df56cf1-c145-4f4e-ba10-85b24d6e7158)
![image](https://github.com/salvo-rs/salvo/assets/73412370/17ad6c28-8b7f-4b98-a4e4-07f16a4cd205)

## 现在：
找不到设置Authentication参数的入口，不清楚是否需要在哪里额外添加参数？
swagger-ui 没有相关设置按钮。
rapidoc 没有开放设置页面，rapidoc目前效果如下
![image](https://github.com/salvo-rs/salvo/assets/73412370/3d4fc21c-2451-4a9b-8c70-03093f5ae88f)

### 代码
代码如下
```rust
let doc = OpenApi::new("RSNS api", "0.0.1")
    .merge_router(&router)
    .security(vec![SecurityRequirement::new("api_oauth2_flow", ["edit:items", "read:items"])]);
```
```rust
/// 获取全部角色列表
#[endpoint(tags("系统->角色"),
    security(
    (),
    ("my_auth" = ["read:items","edit:items"]),
    ("token_jwt" = [])
    )
)]
pub async fn get_all_list(req: &mut Request) -> Res<ListData<SysRoleListModel>> {
    todo!
}
```

### swagger-ui效果展示：
![image](https://github.com/salvo-rs/salvo/assets/73412370/27de213e-0672-47da-8d42-cbabc4d90d48)

### 请求体展示：
![image](https://github.com/salvo-rs/salvo/assets/73412370/1ffdc76e-cd75-460e-a011-056ab938a911)

**Comment by chrislearn** [comment]
我更新了一下 api，现在应该好设置一点，大概是这样：

```rust
    let doc = OpenApi::new("todos api", "0.0.1").add_security_scheme(
        "abc",
        security::OAuth2::with_description(
            [security::Flow::Implicit(security::Implicit::new(
                "https://localhost/auth/dialog",
                security::Scopes::from_iter([("edit:items", "edit my items"), ("read:items", "read my items")]),
            ))],
            "my oauth2 flow",
        ),
    ).merge_router(&router);
```
