### ISSUE TITLE
Make it easy to debug request body

### ISSUE THREAD

**Issue by prabirshrestha** [salvo-rs/salvo#577]
I'm working on integrating and external app and wanted to see what it was sending.

Is it possible to make it easy to do this? Or is there something like `req.parse_body_string()`. For quick debugging would be good if there is an easy way to get string or bytes from body.

```rust
let body = req.take_body();
dbg!(body);
```

**Comment by chrislearn** [comment]
Will give inner debug information if inner can debug.
