### ISSUE TITLE
Is there a way to give name alias for OpenApi query parameter?

### ISSUE THREAD

**Issue by mmittnacht** [salvo-rs/salvo#579]
I would like to ask if there is a way to add parameter alias for OpenApi parameters/Query parameters?

For example:

test: QueryParam<_> would accept $test, if I set alias for it. Is there a way to do it?
Thanks for any help!

**Comment by chrislearn** [comment]
You can add another param called `$test` in endpoint macro, use utoipa way.

And then check is `test` None, if it is None, use `req.query("$test")` get `$test` value.

**Comment by mmittnacht** [comment]
Thank you, will try it!
