### ISSUE TITLE
Would be nice to have validation on OpenAPI

### ISSUE THREAD

**Issue by ollyde** [salvo-rs/salvo#588]
I’m loving this framework, very professional and the best one yet!

Would be nice to show input validation on the API endpoints via OpenAPI.

For example; 
A name value might be capped at length 20. Frontend needs to know this!

**Comment by zhangkai803** [comment]
Hi Ollyde, the validation of params was already supported by openapi schema.

In salvo, you can try this:

```rust
use salvo::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Extractible, Debug, ToSchema)]
#[salvo(extract(default_source(from = "body")))]
pub struct SomeReq {
    // phone: String,
    #[salvo(schema(min_length = 20, max_length = 20))]
    name: String,
    #[salvo(schema(minimum = 1))]
    num: i32
}
```

The schema will looks like:
![image](https://github.com/salvo-rs/salvo/assets/41277964/ce7a4a28-c704-44e6-ac61-46d96bd088f0)

You can discover more schema in [https://github.com/salvo-rs/salvo/blob/main/crates/oapi/src/openapi/schema/mod.rs](https://github.com/salvo-rs/salvo/blob/main/crates/oapi/src/openapi/schema/mod.rs).

**Comment by ollyde** [comment]
@zhangkai803 awesome work!

**Comment by ollyde** [comment]
@zhangkai803 as a random question. Do you know if any code-gen tools for Flutter and TypeScript work with this spec? I might be pushing it hehe.

**Comment by ollyde** [comment]
@zhangkai803 would be great if this was in the docs somewhere!

**Comment by zhangkai803** [comment]
> @zhangkai803 as a random question. Do you know if any code-gen tools for Flutter and TypeScript work with this spec? I might be pushing it hehe.

Most of large language models can generate code for this case. The key is  how to make AI understand your intention clearly. I am using Codegeex in my workflow because it's free and smart enough for me.

**Comment by ollyde** [comment]
@zhangkai803 indeed I use ChatGPT but it's still fairly manual, there are lots of great swagger to Dart/Typescript tools out there where you can write your service automatically. :-)

**Comment by prabirshrestha** [comment]
Might be forking https://github.com/1Password/typeshare to support salvo specific things  would be great. For now I just use it to generate request bodies from rust to typescript.

**Comment by ollyde** [comment]
@prabirshrestha awesome I will check this out. Although defining the exact response type is important for 3rd party clients (we need to define all the errors that can return and bodies)
