### ISSUE TITLE
[OpenAPI Tags]

### ISSUE THREAD

**Issue by ollyde** [salvo-rs/salvo#609]
Would be nice to be able to add tags.
The Rust Docs are hard to read for Macros / Don't show anything.

For example, everything is 'default' right now.

<img width="463" alt="Screenshot 2024-01-07 at 14 12 51" src="https://github.com/salvo-rs/salvo/assets/6940726/a13f370b-d89b-47cf-9fa9-6efebaf516af">

**Comment by chrislearn** [comment]
You can add tags, salvo supported it.
See this example: https://github.com/salvo-rs/salvo/blob/main/examples/oapi-todos/src/main.rs

**Comment by ollyde** [comment]
Thanks for the super quick response.

It doesn't seem to work, I have

```
#[endpoint(tags("test"))]
pub async fn test_input_data(
    res: &mut Response,
    some_request: JsonBody<TestInput>,
) -> ApiResponse<ApiResponseData> {
    // set_ok_data(res, some_request.into_inner());
    ApiResponse {
        status: "status".to_string(),
        message: "message".to_string(),
        data: ApiResponseData {
            some_field: "some value".to_string(),
        },
    }
}

```

But it still says "default"

**Comment by chrislearn** [comment]
I have tested `exampel-opi-todos`, it works.

**Comment by ollyde** [comment]
@chrislearn thanks, indeed I copy pasted the endpoint macro definition and it doesn't show.

I'm using merge router, so perhaps that might break it? I don't know; but it still says 'default' 🙈

**Comment by ollyde** [comment]
@chrislearn sorry my bad. Rust wasn't reporting that it was a duplicate function (not being used)
