### ISSUE TITLE
WARN http response content type header not set for a http 302 response

### ISSUE THREAD

**Issue by 18o** [salvo-rs/salvo#615]
**Describe the bug**
for a http 302 response the response content-type is pointless, but salvo gives warn.

**To Reproduce**
1. start server
2. run ` curl -i https://127.0.0.1:5800/efun`
3. See the WARN

**Expected behavior**

**Screenshots**
![CleanShot 2024-01-10 at 14 29 05@2x](https://github.com/salvo-rs/salvo/assets/14882753/99950174-8ee8-41da-ac46-dbb5f53831b8)

![CleanShot 2024-01-10 at 14 28 51@2x](https://github.com/salvo-rs/salvo/assets/14882753/f84a4010-f1a1-4236-baaf-84753c9a6252)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: curl
 - Version: 8.4.0

**Additional context**

**Comment by chrislearn** [comment]
Fixed by #616
