### ISSUE TITLE
Find a way to rename OpenAPI object and operation globally

### ISSUE THREAD

**Issue by ollyde** [salvo-rs/salvo#619]
On the swagger spec the operationIds are very long

<img width="975" alt="Screenshot 2024-01-10 at 18 47 46" src="https://github.com/salvo-rs/salvo/assets/6940726/d3169bc1-287c-481d-94aa-cbd561ba54b7">

This results in very long auto generated code

<img width="739" alt="Screenshot 2024-01-10 at 18 48 07" src="https://github.com/salvo-rs/salvo/assets/6940726/ca20c83e-9bb6-4366-8742-eaf40ad007d9">

We need away to reduce it.

**Comment by chrislearn** [comment]
You can rename your operation_id for example:

```rust
#[endpoint(operation_id="AAAAAAA", tags("todos"), status_codes(200, 404))]
pub async fn update_todo(id: PathParam<u64>, updated: JsonBody<Todo>) -> Result<StatusCode, StatusError> {
...
}

```

**Comment by ollyde** [comment]
@chrislearn yes indeed but it’s also on objects like return types; would be nice to config the root so it’s smaller across the whole project automatically :-)

**Comment by chrislearn** [comment]
You can use your custom `Namer` to define your rename rule globally.

https://github.com/salvo-rs/salvo/blob/main/crates/oapi/src/naming.rs

I just don't have time to polish the documentation. PRs for documentation are welcome.
