### ISSUE TITLE
The Standard 404 error is not logged with the default logger

### ISSUE THREAD

**Issue by rustafariandev** [salvo-rs/salvo#620]
**Describe the bug**
The Standard 404 error is not logged with the default logger

**To Reproduce**
```rust
use salvo::prelude::*;

#[handler]
async fn hello() -> &'static str {
    "Hello World"
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().init();

    let router = Router::new().hoop(Logger::new()).get(hello);
    let acceptor = TcpListener::new("127.0.0.1:5800").bind().await;
    Server::new(acceptor).serve(router).await;
}

```

**Expected behavior**
The 404 is logged when an unknown page is hit.

**Comment by rustafariandev** [comment]
It still does not work in the latest release

**Comment by chrislearn** [comment]
You need to add middleware to serive: https://github.com/salvo-rs/salvo/blob/main/examples/logging/src/main.rs
