### ISSUE TITLE
使用openapi通过query提取参数，序列化失败

### ISSUE THREAD

**Issue by Linken-code** [salvo-rs/salvo#624]
接口传参名称为cameraSn或者camera_sn，使用openapi通过query提取参数camera_sn，结果报错序列化失败。
serde的三种别名方式尝试过了，全部失败。
![1704946739658](https://github.com/salvo-rs/salvo/assets/71937862/aa28ea10-507c-4178-bb03-5da00e32e4aa)

![1704946784998](https://github.com/salvo-rs/salvo/assets/71937862/15d068dd-b0a8-426f-a2ae-92bc977c13a6)

![1704946981951](https://github.com/salvo-rs/salvo/assets/71937862/b8cf48f7-ec8c-4ef2-8958-2b33fafdbc3f)

如果不使用serde别名，接口传参名称改为camera_sn，则提取query参数成功

![1704947041954](https://github.com/salvo-rs/salvo/assets/71937862/127fab94-f5a8-479c-8698-c5fbe85a3841)

**Comment by chrislearn** [comment]
应该早上修复了 你拿线上版本测试看看呢

**Comment by Linken-code** [comment]
> 应该早上修复了 你拿线上版本测试看看呢

用git的最新版本，测试了一遍，已经修复了
