### ISSUE TITLE
[Feature Request] Support for rate limiting headers

### ISSUE THREAD

**Issue by TheAwiteb** [salvo-rs/salvo#626]
### Description
Will be nice to have support for rate limiting headers like `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` in the response headers.

### Motivation
I want to use the rate limiting headers in my application.

### Additional context
The rate limiting headers are very useful for developers. You can read more about rate limiting headers [here](https://www.ietf.org/archive/id/draft-polli-ratelimit-headers-02.html#name-header-specifications).

### Possible implementation
I think the best way to implement this feature is to add a new field for `RateLimiter` struct, like `with_headers` and if it's true, the rate limiting headers will be added to the response headers, it's should be false by default.

**Comment by TheAwiteb** [comment]
I can work on it if it is approved. Please tell me if I can start working on it or not

**Comment by chrislearn** [comment]
I want to know how you plan to implement it. There is already a crate with rate limte. Is it to enhance its functionality?

**Comment by TheAwiteb** [comment]
I will add it to [`QuotaGetter`](https://docs.rs/salvo-rate-limiter/latest/salvo_rate_limiter/trait.QuotaGetter.html), but I think this will affect [`impl<Key, T> QuotaGetter<Key> for T`](https://docs.rs/salvo-rate-limiter/0.64.0/src/salvo_rate_limiter/quota.rs.html#114-129) I think we should delete it, and let the user implement it for it's quota type

**Comment by chrislearn** [comment]
Maybe we need to change RateGuard's verify function, add Response's headers as the second arg:

```rust
pub trait RateGuard: Clone + Send + Sync + 'static {
    type Quota: Clone + Send + Sync + 'static;
    async fn verify(&mut self, quota: &Self::Quota, headers: &mut HeaderMap) -> bool;
}
```
