### ISSUE TITLE
oapi 的 QueryParam 不支持 struct类型

### ISSUE THREAD

**Issue by z91300** [salvo-rs/salvo#628]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/salvo-rs/salvo/assets/73412370/1c4316af-ac50-4a09-a896-3f191e94cfd0)

**Describe the solution you'd like**
QueryParam 支持 struct 传参并且能够在openapi中能够正常显示对应的字段属性

**Describe alternatives you've considered**

还是说只能如 example-oapi-todos 中的list示例一样列举出所有字段
```rust
pub async fn list_todos(offset: QueryParam<usize, false>, limit: QueryParam<usize, false>) -> Json<Vec<Todo>> {
}
```

**Additional context**

**Comment by chrislearn** [comment]
可以使用 `ToParameters`， 把所有的参数集合起来存放在一个或者多个 struct 中，比如：

```rust
#[derive(ToParameters, serde::Deserialize)]
#[salvo(parameters(default_parameter_in = Query))]
struct Filter {
    #[salvo(parameter(value_type = Id))]
    id: String
    #[salvo(parameter(max_length = 10, min_length = 5, pattern = "[a-z]*"))]
    value: String,
}
```
