### ISSUE TITLE
Can we make the `SendTarget` a public trait?

### ISSUE THREAD

**Issue by TheAwiteb** [salvo-rs/salvo#632]
In my case, I want to test a endpoint that needs the request IP address, but by default the `Request` makes the IP address `SocketAddr::Unknown`, so I can't test it. I want to change the IP of the local address to a known one, and I can do it, The problem is that I want to use the `SendTarget::call` function of the `Service` to test the endpoint, but it's private.

This is the code I want to use: it's a function that sends a request to the API, but it's returns an error because the `call` function is private.

```rust
/// Function to send a request to the API.
pub async fn send(service: &Service, path: &str, method: Method) -> Response {
    let mut req = RequestBuilder::new(format!("{}/{}", API_URL, path), method).build();
    *req.local_addr_mut() = salvo::core::conn::SocketAddr::IPv4(std::net::SocketAddrV4::new(
        std::net::Ipv4Addr::new(127, 1, 1, 1),
        5802,
    ));

    service.call(req).await
}
```

NOTE: I can work on it if it is approved

**Comment by TheAwiteb** [comment]
The trait itself is public, put we need to `pub use` it [here](https://github.com/salvo-rs/salvo/blob/140584199b56c1e012df189868cc7210a7cd179d/crates/core/src/test/mod.rs#L7) and [here](https://github.com/salvo-rs/salvo/blob/140584199b56c1e012df189868cc7210a7cd179d/crates/core/src/test/request/mod.rs#L3)

**Comment by chrislearn** [comment]
No problem, you can submit a PR.
