### ISSUE TITLE
Cannot override non-schema type

### ISSUE THREAD

**Issue by ollyde** [salvo-rs/salvo#638]
I'm using MongoDB and would like to expose some objects to the front-end.

Unfortunately they use a custom data type called "ObjectId" which is annoying.

It doesn't support ToSchema. My attempts to emulate it have failed.

I try the following 

```
fn custom_type() -> Object {
    Object::new()
        .schema_type(SchemaType::String)
        .format(SchemaFormat::Custom("email".to_string()))
        .description("this is the description")
}

#[derive(Debug, Serialize, Deserialize, Clone, Validate, ToSchema)]
pub struct Device {
    #[salvo(parameter(schema_with = custom_type))]
    pub _id: ObjectId,
} 
```

I still get the error

`the trait bound `bson::oid::ObjectId: salvo::prelude::ToSchema` is not satisfied`

Any ideas?

**Comment by chrislearn** [comment]
How about this:

```rust
#[derive(Debug, Serialize, ToSchema)]
pub struct ResBody {
    #[salvo(schema(value_type = String, additional_properties = true))]
    pub user_id: UserId,
}
```

**Comment by ollyde** [comment]
@chrislearn thanks that works great!

Now i have to figure out the next error, no sure if this is Mongo or Salvo related, can't find any stack trace.

Kind: expected map containing extended-JSON formatted ObjectId, instead found { "id": [101, 164, 92, 104, 163, 255, 148, 98, 60, 96, 36, 28] }, labels: {}
