### ISSUE TITLE
I noticed a massive use of unwrap() in Salvo source code (670 unwrap )

### ISSUE THREAD

**Issue by rxdiscovery** [salvo-rs/salvo#649]
Hello,

I've just discovered this wonderful project. I've been looking for a framework with good openapi support, I found two promising frameworks **Salvo** and **Poem** in the Rust ecosystem.

I want to redevelop a project using Salvo, but there's a small detail that's bothering me; while analyzing its source code, I noticed a massive use of unwrap() without exception handling.

there are 670 unwrap() in the code, all in 143 files.

This is a major problem for stability, as programs intended for production use cannot tolerate a shutdown due to an exception not handled by the framework.

I really want to help by adding as many "match xxx {}", but the project is too big, and it would be nice to take into account that unwrap() is only used temporarily to save time, and not for definitive code.

Note that unwrap() adds code containing file paths, so it records in the final executable all data that could determine the origin of the exception, including the complete path of the source files, which gives the developer's name:  ex: `/home/{user_name}/projet/XXXX/file.rs`

To verify what I'm saying, you can display all the strings contained in the executable like this:
```bash
cargo build --release
strings ./target/release/{{  project(.exe)  }}  >  str.txt
vi str.txt
```

Thank you very much for your efforts  :+1:  , I'll try to modify the parts of the code containing "unwrap()" little by little and send the modifications here, it would be nice if we all got involved to go faster.

**Comment by chrislearn** [comment]
I hope you have carefully looked at the code. Most of the unwrap in it is only in the documentation and unit tests.
In addition, there are a few places where unwrap is needed.

**Comment by rxdiscovery** [comment]
Hello,

of course not all of them are in the main code, the existence of a single unwrap is enough to break the developer's privacy and create the potential risk of an uncontrolled crash.

here are some examples of code containing unwraps :

```rust
impl Default for Compression {
    #[inline]
    fn default() -> Self {
        #[allow(unused_mut)]
        let mut algos = IndexMap::new();
        #[cfg(feature = "zstd")]
        algos.insert(CompressionAlgo::Zstd, CompressionLevel::Default);
        #[cfg(feature = "gzip")]
        algos.insert(CompressionAlgo::Gzip, CompressionLevel::Default);
        #[cfg(feature = "deflate")]
        algos.insert(CompressionAlgo::Deflate, CompressionLevel::Default);
        #[cfg(feature = "brotli")]
        algos.insert(CompressionAlgo::Brotli, CompressionLevel::Default);
        Self {
            algos,
            content_types: vec![
                "text/*".parse().unwrap(),
                "application/javascript".parse().unwrap(),
                "application/json".parse().unwrap(),
                "application/xml".parse().unwrap(),
                "application/rss+xml".parse().unwrap(),
                "application/wasm".parse().unwrap(),
                "image/svg+xml".parse().unwrap(),
            ],
            min_length: 0,
            force_priority: false,
        }
    }
}
```

```rust
#[inline]
fn status_error_json(code: StatusCode, name: &str, brief: &str, cause: Option<&str>) -> String {
    #[derive(Serialize)]
    struct Data<'a> {
        error: Error<'a>,
    }
    #[derive(Serialize)]
    struct Error<'a> {
        code: u16,
        name: &'a str,
        brief: &'a str,
        cause: &'a str,
    }
    let data = Data {
        error: Error {
            code: code.as_u16(),
            name,
            brief,
            cause: cause.unwrap_or(EMPTY_CAUSE_MSG),
        },
    };
    serde_json::to_string(&data).unwrap() // <--------------------------------------------- /!\
}
```
I've noticed that you've sent patches correcting some unwrap with unwrap_or_default, thank you very much :+1: . 

if you want, we can share the work, you give me a list of modules to clean them from unwrap, so we don't have to do the job twice.

**Comment by chrislearn** [comment]
Mime does not have function like `Mime::from_static_str`, so if you do not want use `unwrap`, how to change this code?

Even if all unwrap is removed from salvo, salvo cannot guarantee that unwrap is not used in all dependent crates.
If you feel there is a problem with unwrap, should you file an issue with rust instead of salvo?

**Comment by rxdiscovery** [comment]
Why not use this :

```rust
mimes! {
    STAR_STAR, "*/*", 1;

    TEXT_STAR, "text/*", 4;
    TEXT_PLAIN, "text/plain", 4;
    TEXT_PLAIN_UTF_8, "text/plain; charset=utf-8", 4, None, 10;
    TEXT_HTML, "text/html", 4;
    TEXT_HTML_UTF_8, "text/html; charset=utf-8", 4, None, 9;
    TEXT_CSS, "text/css", 4;
    TEXT_CSS_UTF_8, "text/css; charset=utf-8", 4, None, 8;
    TEXT_JAVASCRIPT, "text/javascript", 4;
    TEXT_XML, "text/xml", 4;
    TEXT_EVENT_STREAM, "text/event-stream", 4;
    TEXT_CSV, "text/csv", 4;
    TEXT_CSV_UTF_8, "text/csv; charset=utf-8", 4, None, 8;
    TEXT_TAB_SEPARATED_VALUES, "text/tab-separated-values", 4;
    TEXT_TAB_SEPARATED_VALUES_UTF_8, "text/tab-separated-values; charset=utf-8", 4, None, 25;
    TEXT_VCARD, "text/vcard", 4;

    IMAGE_STAR, "image/*", 5;
    IMAGE_JPEG, "image/jpeg", 5;
    IMAGE_GIF, "image/gif", 5;
    IMAGE_PNG, "image/png", 5;
    IMAGE_BMP, "image/bmp", 5;
    IMAGE_SVG, "image/svg+xml", 5, Some(9);

    FONT_WOFF, "font/woff", 4;
    FONT_WOFF2, "font/woff2", 4;

    APPLICATION_JSON, "application/json", 11;
    APPLICATION_JAVASCRIPT, "application/javascript", 11;
    APPLICATION_JAVASCRIPT_UTF_8, "application/javascript; charset=utf-8", 11, None, 22;
    APPLICATION_WWW_FORM_URLENCODED, "application/x-www-form-urlencoded", 11;
    APPLICATION_OCTET_STREAM, "application/octet-stream", 11;
    APPLICATION_MSGPACK, "application/msgpack", 11;
    APPLICATION_PDF, "application/pdf", 11;

    MULTIPART_FORM_DATA, "multipart/form-data", 9;
}
```

here's a proposal; more efficient and with no risk of exception 

```rust
        Self {
            algos,
            content_types: vec![
                salvo_core::http::mime::TEXT_STAR,
                salvo_core::http::mime::APPLICATION_JAVASCRIPT,
                salvo_core::http::mime::APPLICATION_JSON,
                salvo_core::http::mime::TEXT_XML,
                "application/xml".parse().unwrap_or(salvo_core::http::mime::TEXT_XML),
                "application/rss+xml"
                    .parse()
                    .unwrap_or(salvo_core::http::mime::STAR_STAR),
                "application/wasm".parse().unwrap_or(salvo_core::http::mime::STAR_STAR),
                salvo_core::http::mime::IMAGE_SVG,
            ],
            min_length: 0,
            force_priority: false,
        }
```


I've added TEXT_XML ( application/xml <-> text/xml )

**Comment by rxdiscovery** [comment]
You also have this directive to prohibit compilation if unwraps exist in the code.

```rust
#![deny(clippy::unwrap_used)]
```

ref: https://rust-lang.github.io/rust-clippy/master/#/unwrap_used
