### ISSUE TITLE
Rustls backend loads only the first certificate from file

### ISSUE THREAD

**Issue by AdrianEddy** [salvo-rs/salvo#652]
**Describe the bug**
When loading a certificate file which contains multiple certificates (main, intermediate and root), only the first certificate is loaded, which leads to TLS issues with some browsers and this warning on SSLChecker:
![image](https://github.com/salvo-rs/salvo/assets/3849067/6ef43dfa-09ae-4db0-addc-ef386fe49b78)

This is caused by the use of `.next()` instead of `collect()` [here](https://github.com/salvo-rs/salvo/blob/c80c1697c8fef958da6151d7cdf3c39903192cd7/crates/core/src/conn/rustls/config.rs#L102)

This doesn't happen with openssl backend

**To Reproduce**
1. Run the rustls example
2. Provide a certificate file with multiple certificates
3. Test the server with [SSLChecker](https://www.sslshopper.com/ssl-checker.html)
4. Observe that only one certificate is listed

**Expected behavior**
I expect it to load all certificates from the file

**Comment by chrislearn** [comment]
Changed to `collect()` but not sure it is fixed. Can you check it again?

**Comment by AdrianEddy** [comment]
Yes it's good now, thank you!
