### ISSUE TITLE
防御慢速HTTP攻击

### ISSUE THREAD

**Issue by luyikk** [salvo-rs/salvo#661]
参考问题连接：

https://github.com/hyperium/hyper/issues/2457

h2 当tcp连接上来后，需要对tls验证进行timeout检测，一般是5秒，如果大于5秒没用完成tls验证，需要对连接杀死，并释放资源，tls验证过后，需要对http header 读取进行 timeout 检测，一般5秒，如果超时需要对连接杀死，并释放资源， http header过后需要对body 进行timeout检测，一般5秒，如果超时需要对连接杀死，并释放资源。 以上5秒需要可配置

h1.1 没用tls这一步

h3 目前不清楚，但对应的超时检测 释放相关的资源 应该也是存在的

**Comment by chrislearn** [comment]
fuse 分支，尚未测试，你一般用什么工具测试这种慢网速或者 tls 验证问题？

h3 应该还好，一般连接重用，好像一个客户端一般建立一个连接。

另外安全防护是一个复杂的问题，框架层面很难完全解决，甚至于可以说本身就没法解决，只能说加大点攻击难度而已。

**Comment by luyikk** [comment]
telnet ip 端口 即可 看看多久关闭 socket 链接



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chrislearn Young ***@***.***&gt;
发送时间: 2024年2月8日 15:06
收件人: salvo-rs/salvo ***@***.***&gt;
抄送: luyikk ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [salvo-rs/salvo] 防御慢速HTTP攻击 (Issue #661)





 
fuse 分支，尚未测试，你一般用什么工具测试这种慢网速或者 tls 验证问题？
 
h3 应该还好，一般连接重用，好像一个客户端一般建立一个连接。
 
另外安全防护是一个复杂的问题，框架层面很难完全解决，甚至于可以说本身就没法解决，只能说加大点攻击难度而已。
