### ISSUE TITLE
Redirect a PUT

### ISSUE THREAD

**Issue by yamelsenih** [salvo-rs/salvo#677]
Hello everyone. I am trying redirect a PUT request based on query parameters. Exists a way to redirect a PUT with the body as file?

My example try redirect a PUT with a big file yo other URL that can changed depending of query parameters and a third party service.

Here is my example: https://github.com/adempiere/s3_gateway_rs/blob/main/src/bin/server.rs#L63

**Comment by yamelsenih** [comment]
hello

**Comment by chrislearn** [comment]
I don't quite understand your needs. What kind of functions do you need the framework to achieve? Is it like a reverse proxy or something else? Reverse proxy functionality is already supported.
