### ISSUE TITLE
HTTP/1.1 Always has HTTP Scheme

### ISSUE THREAD

**Issue by mateusvmv** [salvo-rs/salvo#699]
**Describe the bug**
Connections made through HTTP/1.1 always end up with an http scheme in the uri, which breaks the Force HTTPS feature, as it relies on the URI to determine whether it should redirect or not.

**To Reproduce**
1. Start a new Salvo server with logging enabled
2. curl --get 'https://my-server' --http1.1 --tlsv1.3 --verbose
3. Notice that the server thinks the scheme is http regardless of the TLS

**Expected behavior**
The server should be able to handle https connections through HTTP/1.1 without redirecting them to the same URL in a loop. This happens because the server has the wrong URI.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser curl (or any that doesn't choose HTTP/2 over HTTP/1.1)

**Additional context**
The server is only listening on :443.
The listener on that port is an AcmeQuinnListener, on top of a linux socket.

**Comment by chrislearn** [comment]
done via #702
