### ISSUE TITLE
pls support monoio

### ISSUE THREAD

**Issue by ouvaa** [salvo-rs/salvo#704]
pls support monoio
https://github.com/bytedance/monoio

**Comment by chrislearn** [comment]
I feel that this runtime is not popular, and the workload of adding a runtime is also huge.

**Comment by ouvaa** [comment]
@chrislearn currently salvo is very slow on techempower benchmark. possible to add this runtime? it'll make salvo the top rust web framework in the world

**Comment by ouvaa** [comment]
@chrislearn but monoio is really fast. is there a possibility you can consider adding this in future? i've checked a lot of frameworks and salvo is one of the best for developer use. my only issue is the slow speed. it's very slow to use tokio. i hope u can consider using monoio. can this be part of the roadmap?
