### ISSUE TITLE
is going the fastest on the roadmap?

### ISSUE THREAD

**Issue by ouvaa** [salvo-rs/salvo#706]
salvo is currently lagging behind in req/s for plaintext on techempower and only 25% from the fastest gnet.

was wondering if pushing to at least 80% is what salvo's roadmap or first. just curious

**Comment by ouvaa** [comment]
really looking forward to salvo having monoio runtime

**Comment by chrislearn** [comment]
Too many functions rely on tokio, and supporting monoio seems to be a task that cannot be completed in the short term. Moreover, monoio is not a widely used runtime, so we will not consider it for the time being.
