### ISSUE TITLE
monoio integration. how many coffee/sponsorship is this worth it?

### ISSUE THREAD

**Issue by ouvaa** [salvo-rs/salvo#715]
@chrislearn salvo is slow on techempower. let's make this one of the fastest rustlang framework.

it's really great but it's slower than golang. i can sponsor more coffees for this. please consider adding it into salvo and do mention how much is needed for this to happen. thx!

**Comment by chrislearn** [comment]
The performance of Salvo mainly depends on hyper, and in theory it will not be much slower than the test implemented by pure hyper.
As for why the plaintext test performance of hyper-based frameworks is poor, there is an issue on hyper: https://github.com/hyperium/hyper/issues/1169

As far as I know, monoio seems to be an immature runtime, and its usage is very small. Unlike underlying libraries such as hyper, salvo relies on many third-party libraries. To ensure that all functions are normal when switching runtimes, many third-party libraries may be required to be runtime-independent, which seems impossible.

**Comment by chrislearn** [comment]
monoio may claim a huge performance improvement, however, I would like to ask if there are rigorous tests to confirm this. Or have you tested the performance difference between tokio and monoio based on hyper?

If you test locally, the performance of salvo should be faster than any Go language framework.

**Comment by ouvaa** [comment]
@chrislearn salvo is around 16% slower than xitca, xitca is 16% slower than monoio.
it's the thread per core nature of the software. techempower reflects very clearly.

if you are adamant on implementing monoio, can you please do thread per core then? but i suggest you do monoio integration. will you be willing to implement thread per core for salvo? i can sponsor this just for this feature.

please do monoio so we dont have to upgrade or switch another framework anymore. it's the fastest runtime tested. i understand your rationale but thread per core is needed else performance wise golang can match salvo using prefork mode rather easily for higher number of cores.

**Comment by ouvaa** [comment]
@chrislearn sorry i made a mistake, in terms of cpu usage, salvo is 300% while monoio does 257% and faster by a bit BUT i'm sure because it's using thread per core and remove an additional layer, it's cpu processing power can handle more requests.

so meaning it's still 15% more performant than salvo. given more cpu mores, the results will be more evident as like techempower's plaintext which uses 24 cores but if u go higher like 192 cores etc. salvo cpu usage will be totally under utilized. meaning, compared with golang prefork mode, it's better to use golang for 28 threads or more. 

Salvo cpu usage 300%

taskset -c 4,5  wrk -t 2 -d 10 http://127.0.0.1:5800/
Running 10s test @ http://127.0.0.1:5800/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    30.92us   11.72us   1.71ms   82.96%
    Req/Sec   135.72k     9.10k  140.09k    95.05%
  2726673 requests in 10.10s, 332.85MB read
Requests/sec: 269978.66
Transfer/sec:     32.96MB



monoio

cpu usage 257%

taskset -c 4,5  wrk -t 2 -d 10 http://127.0.0.1:8080/
Running 10s test @ http://127.0.0.1:8080/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    32.63us   49.18us   5.87ms   99.80%
    Req/Sec   135.86k     8.47k  140.25k    95.05%
  2731050 requests in 10.10s, 226.59MB read
Requests/sec: 270399.84
Transfer/sec:     22.43MB

**Comment by ouvaa** [comment]
@chrislearn it may seem a lot of req/s but doing so as part of antiddos protection. also, it's a "hello world" result generation so looking to extract maximum performance from iot device running salvo (for added antiddos protection).

i need the speed and efficiency. possible to consider adding monoio? i can sponsor this. do mention how much u think is worth the sponsorship to make salvo truly good on techempower.

**Comment by chrislearn** [comment]
To be honest, it would certainly be nice to support more runtimes. But, as I said before, this is very difficult to implement. After all, salvo is an open source project and does not have funding or company support. So I can’t guarantee that I will invest too much time in this later. So I can't give any guarantee as to whether monoio will be supported in the future.

If you really think this project is good and want to donate to this project, I welcome it. It's just that I won't make any promises just because I want to get donations. This will put more pressure on my already stressful life. I hope you understand.

**Comment by ouvaa** [comment]
@chrislearn i understand. but do mention how much you think is possible for this to happen. the donation / sponsorship part etc.

**Comment by chrislearn** [comment]
Personally, I don't care about this little performance difference. After adding business logic, this performance difference becomes minimal. So in my opinion, it is not necessary to learn from xitca-web, at least for me personally.

As for what kind of changes tokio will make, I don’t know.

If monoio cannot become a mainstream runtime, support for it will not be added in the short term. I just asked the author of monoio. If salvo supports monoio, io interface and uses tokio io dependent library, this part will be very difficult. This has nothing to do with the amount of the donation, it’s just that my time and ability are limited.
