### ISSUE TITLE
ChatGPT "compatibility".

### ISSUE THREAD

**Issue by ouvaa** [salvo-rs/salvo#718]
i've tried other frameworks, other than golang which can still generate useful results from chatgpt.

can you make it easy for chatgpt to understand your code so we dont have to ask here? maybe write more comments / reference so that chatgpt can really help out more.

currently, chatgpt is not that helpful

**Comment by chrislearn** [comment]
Sorry, I don't work in openai and I don't know how to make chatgpt smarter in answering salvo related questions.
