### ISSUE TITLE
Generic response (openapi)

### ISSUE THREAD

**Issue by rxdiscovery** [salvo-rs/salvo#722]
Hello,

I have api that return response encapsulated in a struct response, but Salvo/openapi does not detect the generic type, and concider it a string.

```rust
#[endpoint(
    operation_id = "get_all_cities",
    tags("city"),
    status_codes(200, 400, 401, 403, 500)
)]
pub async fn get_all_cities() -> Result<ApiResponse<Vec<CityDTO>>, StatusError> {
....
```

it gives me this: 
![salvooap](https://github.com/salvo-rs/salvo/assets/131091294/5b94ef4d-192e-4a0f-a350-d5e92787c9ab)

normally the **data** field here is : **Vec\<CityDTO>**  not **String**

it transforms `ApiResponse<Vec<CityDTO>>` into a String

here is the ApiResponse code :

```rust
use std::fmt::Debug;

use salvo::{
    http::{header::CONTENT_TYPE, HeaderValue},
    oapi::{ToResponse, ToSchema},
    writing::Json,
    Response, Scribe,
};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, ToResponse)]
pub struct ApiResponse<T: Serialize + ToSchema + Send + 'static> {
    // + Send + 'static
    /// The status used for the frontend, for example user-not-found, or need-access, etc
    pub status: String,
    /// Developer friendly message, not used for UI
    pub message: String,
    /// The data returned
    pub data: T,
}

impl<T: Serialize + ToSchema + Send + 'static> ApiResponse<T> {
    pub fn new(status: impl Into<String>, message: impl Into<String>, data: T) -> Self {
        ApiResponse {
            status: status.into(),
            message: message.into(),
            data,
        }
    }
}

impl<T: Serialize + ToSchema + Send + 'static> Scribe for ApiResponse<T> {
    fn render(self, res: &mut Response) {
        res.headers_mut().insert(
            CONTENT_TYPE,
            HeaderValue::from_static("application/json; charset=utf-8"),
        );
        res.render(Json(self));
    }
}
```

he always thinks of the "T" as a string

Thank you very much for helping me solve this problem, it's blocking me, because I'm using code generation via swagger, but if all the generics are considered as Strings, I can't use the code.

I migrated a whole project from ActixWeb+Utoipa to Salvo, but now I'm blocked on this point.

**Comment by chrislearn** [comment]
Please provide the smallest reproducible repository url or zip file.

**Comment by rxdiscovery** [comment]
I will prepare a test project and upload it, thank you in advance.
