### ISSUE TITLE
如何集成casbin访问控制到中间件里去啊？

### ISSUE THREAD

**Issue by joyoes** [salvo-rs/salvo#734]
能不能把casbin权限访问控制加集成到中间件里去啊？想实现基于角色访问控制和数据操作权限操作，结果不知道如何集成
框架自身能不能在下个版本里集成进去啊？

**Comment by chrislearn** [comment]
你照着 https://github.com/casbin-rs/poem-casbin 造一个应该没啥难度吧。

**Comment by hsluoyz** [comment]
@joyoes please refer to salvo-casbin: https://github.com/casbin-rs/salvo-casbin
