### ISSUE TITLE
UNSPECIFIED Ipv4 and Ipv6 use same port crash in centos

### ISSUE THREAD

**Issue by xiaomujin** [salvo-rs/salvo#741]
**Describe the bug**
UNSPECIFIED Ipv4 and Ipv6 use same port crash in centos

**To Reproduce**

**Expected behavior**

**Screenshots**
```
thread 'main' panicked at /root/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/salvo_core-0.66.2/src/conn/mod.rs:177:44:
bind failed: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Desktop (please complete the following information):**
 - OS: win11
 - Version rustc 1.79.0-nightly (1684a753d 2024-04-01)
 - salvo 0.66.2

**Comment by chrislearn** [comment]
这个不是 salvo 的 bug，你直接用标准库里面的 TcpListener 也是一样。
你可以查看关于 IPv4-mapped IPv6 address 相关的问题。
