### ISSUE TITLE
cors not working

### ISSUE THREAD

**Issue by mdddj** [salvo-rs/salvo#753]
复现仓库 https://github.com/mdddj/d_blog
```rs
pub fn cors_middleware() -> CorsHandler {
    let cors_handler = Cors::new()
        .allow_origin(AllowOrigin::any())
        .allow_methods(AllowMethods::any())
        .allow_headers(AllowHeaders::any())
        .into_handler();
    cors_handler
}

```
1.启动salvo
```bash
cargo run
```
2.启动前端
```bash
cd admin && pnpm install && pnpm run dev
```
3.打开: http://localhost:8000/user/login
4.点击登录按钮浏览器控制台报错cors

**Comment by oryjk** [comment]
你好，请问是如何解决的呢？这个是我的配置
` let cors = Cors::new()
        .allow_origin(cors::Any)
        .into_handler();
`
`  let service = Service::new(router).hoop(cors);`

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/blob/main/examples/cors/src/main.rs

可以看这个例子
