### ISSUE TITLE
JWT模块中对数据结构有必须定义`expr`字段要，文档没有说明且易引起用户误用

### ISSUE THREAD

**Issue by xmh0511** [salvo-rs/salvo#757]
https://salvo.rs/book/middlewares/jwt-auth.html
````rust
#[derive(Debug, Serialize, Deserialize)]
pub struct JwtClaims {
    username: String,
    exp: i64,  // #1
}
````
如果用户没有写`exp`或者是其他名称，那么生成的JWT会处于一直失效状态(即无法通过验证)。
> jwt auth error error=Error(MissingRequiredClaim("exp"))

`exp`应该是`salvo`内部JWT实现细节, 不应该暴露给用户定义。 或许salvo应该通过定义一个工具类型如`JwtPayload<T:DeserializeOwned+Send+'static>{claims:T,exp:i64)`包装用户的`JwtClaims`, 并且用户可以通过接口设置内部`exp`时间。

**Comment by chrislearn** [comment]
Salvo 并没有说一定要你的结构体内定义 exp. 而是 jsonwebtoken 这个库的 Validation 默认需要验证这个字段。
https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.Validation.html#structfield.validate_exp

如果你并不需要验证这个字段，可以使用 [ConstDecoder::with_validation](https://docs.rs/salvo-jwt-auth/latest/salvo_jwt_auth/struct.ConstDecoder.html#method.with_validation) 方法使用自己自定义的 Validation.

这里并不打算改变 jsonwebtoken 的这种默认行为，否则可能会有安全问题。
