### ISSUE TITLE
Why write status code twice?

### ISSUE THREAD

**Issue by brussee** [salvo-rs/salvo#762]
The OpenAPI spec integration in this framework looks really great, but I have a question:

Why is it necessary to write the status code twice? In the `return` statement and in the `endpoint` macro, see example from  https://github.com/salvo-rs/salvo/blob/main/examples/oapi-todos/src/main.rs#L89:

```rs
#[endpoint(tags("todos"), status_codes(201, 409))]
pub async fn create_todo(req: JsonBody<Todo>) -> Result<StatusCode, StatusError> {
    tracing::debug!(todo = ?req, "create todo");

    let mut vec = STORE.lock().await;

    for todo in vec.iter() {
        if todo.id == req.id {
            tracing::debug!(id = ?req.id, "todo already exists");
            return Err(StatusError::bad_request().brief("todo already exists"));
        }
    }

    vec.push(req.into_inner());
    Ok(StatusCode::CREATED)
}
```

**Comment by chrislearn** [comment]
If `status_codes(201, 409)` is not added, it means that the status code returned by this endpoint may be 200, 201, 400, 401, 403, 404, 500... and so on. After adding the constraint, this endpoint only returns the status code. 201 or 409. 

`status_codes(201, 409) ` only provides information for generating openapi documents.

**Comment by brussee** [comment]
Thanks for the quick reply!

Is it possible to automatically detect that only 201 and 409 are returned in this example? (This is what I'm hoping is possible.)

**Comment by chrislearn** [comment]
I couldn't find any way to automatically detect this, have you found any?

**Comment by brussee** [comment]
Perhaps if we wrap the `Result` return type with something like a `EndpointResult` and use an `Enum` with limited options for `Ok` (`StatusCode::201` in this example) and also for `Error` (`StatusError::409` in this example), then the `endpoint` macro can use that information to automatically generate documentation based on these limited `Enum` cases. (With `Enum` here I'm thinking of how the `thiserror` crate wraps multiple errors.)

**Comment by chrislearn** [comment]
Yes, you can use your custom enum type, but create many enum types is more complex than just give code in endpoint.

**Comment by brussee** [comment]
Is there any support for such custom `Enum` types in the `endpoint` macro right now?

This would ideally also enable the type checker to check for unused cases:
For example having `status_codes(200, 201, 409)` where `200` is not actually used automatically giving a warning or error at compile time.

**Comment by chrislearn** [comment]
You can try this this:

```rust
#[derive(salvo_oapi::ToResponses)]
enum UserResponses {
    /// Success response description.
    #[salvo(response(status_code = 200))]
    Success { value: String },

    #[salvo(response(status_code = 404))]
    NotFound,

    #[salvo(response(status_code = 400))]
    BadRequest(BadRequest),

    #[salvo(response(status_code = 500))]
    ServerError(Response),

    #[salvo(response(status_code = 418))]
    TeaPot(Response),
}
```
https://github.com/salvo-rs/salvo/blob/main/crates/oapi/docs/derive_to_responses.md
