### ISSUE TITLE
opanapi 接口组和接口的排序问题

### ISSUE THREAD

**Issue by z91300** [salvo-rs/salvo#773]
**Is your feature request related to a problem? Please describe.**
通过endpoint生成处理的swagger文档默认是按照接口路径的字母顺序排序的，有办法指定顺序吗？以便更好的使用它

**Describe the solution you'd like**
以下是网上找的类似的解决方案，但是我不清楚如何在salvo框架中使用
![image](https://github.com/salvo-rs/salvo/assets/73412370/70f16cc7-53a9-4797-88e8-0618db7a8b74)

**Describe alternatives you've considered**
如果能按照路由注册的顺序排最好的，当然我觉得这实现起来会十分困难，如果没有办法解决也没有关系，并不是很重要的功能，直接关闭这个issue就行

**Additional context**
以下是路由和其生成的swagger顺序效果
![image](https://github.com/salvo-rs/salvo/assets/73412370/d09d48d1-435f-42d8-b8d3-1a8e47119232)

**Comment by chrislearn** [comment]
main 分支已经更新
单独引入 salvo-oapi， 然后开启 feature preserve-order
