### ISSUE TITLE
2 features request. 

### ISSUE THREAD

**Issue by sprappcom** [salvo-rs/salvo#791]
1. can you make it faster than hyper on techempower benchmark?

2. how to have multi threaded mode? e.g. 1 process per cpu core

**Comment by sprappcom** [comment]
@narad-muni how can react js be faster than hyper?

can salvo pls make it much faster? on tech empower benchmark it looks really slow

**Comment by Volkor3-16** [comment]
@sprappcom 

It seems like it already is faster on the techempower benchmark.

Salvo - 10th.
Hyper (hyper-db) 30th

Are you just chasing benchmarks, or are you running into a performance issue?

**Comment by sprappcom** [comment]
@Volkor3-16 i'm running into performance issues.

salvo doing 2mil req/s on hello world vs gnet golang at 7mil. it's slower than hyper here. if i cant get performance out of hello world, how can i expect to add more batteries into it and still have performance?

https://www.techempower.com/benchmarks/#hw=ph&test=plaintext&section=data-r22

**Comment by astoring** [comment]
The results of the benchmark are determined by multiple factors. Please do not judge whether a program is fast or slow based on a single test result.

Objectively speaking, Rust's plain text scores are not high, but as business logic increases, Rust's performance advantage will become more obvious.

https://www.techempower.com/benchmarks/#hw=ph&test=fortune&section=data-r22
For example, in the Fortunes test here, salvo ranks tenth, which is not a bad result. However, the best scores of Rust in the plaintext test have all declined overall.

https://web-frameworks-benchmark.netlify.app/result?l=rust
From this test, we can also see that the scores of Rust frameworks are not much different, and salvo is not much slower than axum.

**Comment by astoring** [comment]
@sprappcom 

First of all, how the test itself is written has a great impact on the results.
In addition, hyper may not be the same version as salvo, and different versions of hyper have different performance.
