### ISSUE TITLE
`required` attribute for salvo_oapi endpoint macro

### ISSUE THREAD

**Issue by YorKnEz** [salvo-rs/salvo#792]
According to [docs](https://github.com/salvo-rs/salvo/blob/main/crates/oapi/docs/endpoint.md#params-attributes) of params_attributes, there is no way of setting the `required` flag of a query param off. I would like an attribute that does that.

For example, I want to be able to say:
```
#[endpoint(parameters(("test" = String, Query, required = false)))]
```

**Comment by chrislearn** [comment]
Use `Option<String>`.

```rust
#[endpoint(parameters(("test" = Option<String>, Query, )))]
```
