### ISSUE TITLE
Error using x86_64-PC-Windows-GNU on Windows

### ISSUE THREAD

**Issue by liaohongxing** [salvo-rs/salvo#81]
**Describe the bug**
Error using x86_64-PC-Windows-GNU on Windows

**To Reproduce**
1. Cargo.toml  add salvo_extra
2. Add LogHandler to Hoop
3. cargo run .

**Expected behavior**
Normal compilation

**Salvo Version**
salvo = "0.22"
salvo_extra = "0.22"

**Screenshots**
![微信截图_20220509152432](https://user-images.githubusercontent.com/35255844/167360667-a487b9fe-3222-4a54-b67e-f19b9cf4a4d3.png)

**Comment by chrislearn** [comment]
This error is happened when compile ring.
Maybe you are not install gcc, Check you gcc version with this command:

```
gcc --version
````

You can use scoop to install gcc first.

https://github.com/briansmith/ring/issues/1034

**Comment by chrislearn** [comment]
用 scoop 安装一下 gcc 就分分钟的事情就可以编译了。

**Comment by liaohongxing** [comment]
我的x86_64-pc-windows-gnu是用rustup-init.exe自带引导安装的, 不是用scoop安装的gcc, 自带这个工具链应该被rust测试过。毕竟x86_64-pc-windows-gnu是Tier 1支持 。

**Comment by chrislearn** [comment]
跟你用什么安装 Rust 无关.  至少运行一下  ```scoop install gcc``` 之后再编译就可以了.
