### ISSUE TITLE
`oapi::ToParameters` trait requires `oapi::Extractible` trait, which is not necessary

### ISSUE THREAD

**Issue by TheAwiteb** [salvo-rs/salvo#838]
The [`salvo_oapi::ToParameters`] trait requires the [`salvo_oapi::Extractible`]
trait, which is not necessary.

I want to use the type as a parameters for OpenAPI, and I don't want to extract
it from the request. So I think the [`salvo_oapi::ToParameters`] trait should not
require the [`salvo_oapi::Extractible`] trait.

Also when I use [`cargo-expand`] on my route, Salvo does not use [`Extractible`][`salvo_oapi::Extractible`]
trait, so I think it is not necessary.

[`salvo_oapi::ToParameters`]: https://github.com/salvo-rs/salvo/blob/f757a7c07d37c5be85021a653db5ebba4fd0425e/crates/oapi/src/lib.rs#L434
[`salvo_oapi::Extractible`]: https://github.com/salvo-rs/salvo/blob/main/crates/core/src/extract/mod.rs#L78
[`cargo-expand`]: https://github.com/dtolnay/cargo-expand

**Comment by chrislearn** [comment]
Because this is normally used as an endpoint parameter, the program automatically parses it and requires it to implement `Extractible`.
