### ISSUE TITLE
Additionally, even when I disable the `http2` feature, the server still handles HTTP/2 requests. I don't think it should behave this way.

### ISSUE THREAD

**Issue by TheAwiteb** [salvo-rs/salvo#853]
Additionally, even when I disable the `http2` feature, the server still handles HTTP/2 requests. I don't think it should behave this way.

_Originally posted by @TheAwiteb in https://github.com/salvo-rs/salvo/issues/851#issuecomment-2274456183_

**Comment by TheAwiteb** [comment]
> These features may cause http2 to be automatically enabled.

Yes I see, do you think changing this is better? because maybe I want my server only support one protocol,

We already emit a compile error if no one of those are enabled 

https://github.com/salvo-rs/salvo/blob/affa8cca48cb98aedeec6767f02373bc1ffa4c5e/crates/core/src/server.rs#L7-L10

**Comment by chrislearn** [comment]
If all these protocols are disabled, what services are you providing?

**Comment by TheAwiteb** [comment]
> If all these protocols are disabled, what services are you providing?

Not all, I only want http2 or only http3, or both together. Do you understand me? Meaning I don't want to support http1 for example,  now the server owner is forced to support http1 while they doesn't want to.

This is a breaking change, so we can implement it in the stable release.

**Comment by chrislearn** [comment]
Your words confuse me. The code here means that as long as you have a feature enabled, there will be no compilation error.

```rust
 #[cfg(not(any(feature = "http1", feature = "http2", feature = "quinn")))] 
 compile_error!( 
     "You have enabled `server` feature, it requires at least one of the following features: http1, http2, quinn." 
 ); 
```

**Comment by TheAwiteb** [comment]
I mean there is no fear of not enabling one of them. Now if I want to support only http2 I can't and I want to.

**Comment by TheAwiteb** [comment]
I have no problem with the issue, and there is no reason why I would not want to support a particular protocol. But surely there is someone who wants to support only http1 or only http2. If you do not see this as the case, you can close the issue.

**Comment by chrislearn** [comment]
What I mean is that you only need to make sure that one feature is turned on, and there will be no compilation errors. Compilation errors will only be reported when any protocol is not supported.
