### ISSUE TITLE
examples build error

### ISSUE THREAD

**Issue by fengbol** [salvo-rs/salvo#86]
1. git clone
2. cd examples/hello-world
3. cargo build
4. failed to resolve: could not find `main` in `tokio` and  `main` function is not allowed to be `async`

error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> examples\hello-world\src\main.rs:20:10
   |
20 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0752]: `main` function is not allowed to be `async`
  --> examples\hello-world\src\main.rs:21:1
   |
21 | async fn main() {
   | ^^^^^^^^^^^^^^^ `main` function is not allowed to be `async`

Some errors have detailed explanations: E0433, E0752.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `example-hello-world` due to 2 previous errors

 - OS:win10
 - Version [1.60]

**Comment by chrislearn** [comment]
You don't need to cd hello-world dir. Just in salvo root dir and run:

```
cargo run --bin example-hello-world
```

Please pull again and I fixed this isssue.

**Comment by fengbol** [comment]
ok,thanks
