### ISSUE TITLE
quick-start中的hello_world 編譯出現問題

### ISSUE THREAD

**Issue by jeromeleong** [salvo-rs/salvo#87]
https://salvo.rs/book/quick-start/hello_world/
quick-start中的hello_world 編譯出現問題

error[E0599]: no method named `unwrap` found for unit type `()` in the current scope
  --> src/main.rs:10:74
   |
10 |     Server::new(TcpListener::bind("127.0.0.1:7878")).serve(router).await.unwrap();
   |                                                                          ^^^^^^ method not found in `()`

之後我看github中的其他例子時， 才發現並不需要unwrap()

**Comment by chrislearn** [comment]
谢谢, 我修复了一下. 可能是之前的旧代码. 网站上的代码基本上是复制的 https://github.com/salvo-rs/salvo/tree/main/examples
后续如果有问题, 可以先到这里面找一下, 看是否有最新的代码, 这个里面的代码都是能正常编译的.
网站上的代码没找到可以检测是否正确的方法, 可能会存在一些低级错误. 如果发现, 可以直接提PR.
网站的源码在这里 https://github.com/salvo-rs/website
