### ISSUE TITLE
Add compression support to websockets

### ISSUE THREAD

**Issue by rxdiscovery** [salvo-rs/salvo#872]
Hello,

It would be very useful to add compression support to websocket to optimize bandwidth, 
here's the header that must be interpreted to activate compression

`Sec-WebSocket-Extensions: permessage-deflate`

Thanks in advance.

**Comment by chrislearn** [comment]
salvo does not implement websocket directly, it depends on tokio-tungstenite, so this requires tokio-tungstenite to provide support.

https://github.com/snapview/tokio-tungstenite/pull/251

**Comment by rxdiscovery** [comment]
@chrislearn Thank you very much for your responsiveness, I'll look into it.
