### ISSUE TITLE
0.71.1: cannot call non-const fn `Identity::new` in constant functions

### ISSUE THREAD

**Issue by sysmat** [salvo-rs/salvo#878]
**Describe the bug**
when compiling I get error (rustc 1.80.1, cargo 1.80.1):

```
cannot call non-const fn `Identity::new` in constant functions
src\index.crates.io-6f17d22bba15001f\tower-0.5.0\src\builder\mod.rs:120:20
```

**To Reproduce**

**Expected behavior**
to compile with 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 11

**Additional context**
working with salvo 0.6

**Comment by chrislearn** [comment]
Try to run `cargo update` will fix it.

**Comment by sysmat** [comment]
@chrislearn thx, it works
