### ISSUE TITLE
Provide ability to setup Content-Type for each file or type in StaticDir

### ISSUE THREAD

**Issue by longzou** [salvo-rs/salvo#881]
In many scenarios, we need to manually specify the Content Type and Content Disposal headers based on file type or file name.

**Comment by chrislearn** [comment]
See the [handler-hoop](https://github.com/salvo-rs/salvo/tree/handler-hoop) branch. My thought is that it is difficult to have a very good way to have fine-grained control over individual files in a directory.
Allowing hoop to be added directly to the `Handler` gives control to the user.
