### ISSUE TITLE
如何通过request动态设置cors ?

### ISSUE THREAD

**Issue by micross** [salvo-rs/salvo#924]
我想通过request动态设置cors, 但是我看了cors的代码并没有request, 大神们，谁懂呀？

**Comment by chrislearn** [comment]
那你就抛弃 cors 中间件直接根据情况写 header 就行吧。

**Comment by micross** [comment]
> 那你就抛弃 cors 中间件直接根据情况写 header 就行吧。

这办法可行。目前看来只能我自己写个中间件了。
