### ISSUE TITLE
proxy forward_url support function  like url_query_getter

### ISSUE THREAD

**Issue by tagore-cai** [salvo-rs/salvo#956]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrislearn** [comment]
Sorry, please provide more specific feature requirements.

**Comment by chrislearn** [comment]
`forward_url` is composed of `upstream`, `url_path_getter`, `url_query_getter`, and they are all customizable, the needs can be completely met through their customization, So I don't plan to implement this。
