### ISSUE TITLE
Error: failed to select a version for the requirement `salvo-cors = "^0.73.0"`

### ISSUE THREAD

**Issue by markcda** [salvo-rs/salvo#962]
**Describe the bug**
Can't use "cors" feature with 0.73.0 version cause of:

```
error: failed to select a version for the requirement `salvo-cors = "^0.73.0"`
candidate versions found which didn't match: 0.72.0, 0.71.1, 0.71.0, ...
location searched: crates.io index
required by package `salvo v0.73.0`
    ... which satisfies dependency `salvo = "^0.73"` (locked to 0.73.0)...
```

**Comment by chrislearn** [comment]
Is it because you are not using the official source and are not synchronized?
This version is in the official source.
https://crates.io/crates/salvo-cors

**Comment by markcda** [comment]
I use only `salvo` with its feature.
What should I check to say clearly that I use the official source? I have this line in Cargo.toml: 

``` 
salvo = { version = "0.73", features = [...] }
```

**Comment by markcda** [comment]
I'll try delete Cargo.lock

**Comment by chrislearn** [comment]
Check your cargo system config file, if you are using windows, it's path is `C:/Users/name/.cargo/config.toml`.

**Comment by markcda** [comment]
> I'll try to delete Cargo.lock

This helps.
