### ISSUE TITLE
真的不需要“rust-toolchain.toml”来管理版本吗？

### ISSUE THREAD

**Issue by immno** [salvo-rs/salvo#972]
默认下载一个最新的版本，其实和`salvo`的1.80是不匹配的，会导致一些潜在的问题：
![image](https://github.com/user-attachments/assets/e84f6698-ae78-4969-a134-f5f6a3cb8e28)
高版本的情况：
![image](https://github.com/user-attachments/assets/69f0506d-789e-4de4-b15e-1251c0f6b96a)
使用`rust-toolchain`就会和项目版本进行匹配：
![image](https://github.com/user-attachments/assets/5a4cf423-6b99-4cef-96f3-a951e83570d4)

对于新参与开发的小伙伴来说，本地的`rustc`版本肯定是多样的，有的可能比`salvo`高，那基本不会出问题，如果有的比`salvo`低，`build`大概率就会出错（我记得我23年第一次拉取`salvo`时，`build`时就出错了,不知道怎么办，当时还是菜鸟）。
总之，我认为对于想要来提交或者新手来说，体验还是挺糟糕的（为什么报错？需要手动调整版本）。
可以参考其他项目,感觉还是挺有必要的：
[openDAL](https://github.com/apache/opendal/blob/main/rust-toolchain.toml)  
[greptimeDB](https://github.com/GreptimeTeam/greptimedb/blob/main/rust-toolchain.toml)
[databend](https://github.com/databendlabs/databend/blob/main/rust-toolchain.toml)

**Comment by chrislearn** [comment]
这个 rust-toolchain.toml 是否是强制必须找个版本的 rust？ 还是说高于这个版本的都可以？
如果是强制，肯定不能添加。

**Comment by immno** [comment]
是强制和指定的版本的匹配，是最低版本。我理解是开发时需要的版本，`salvo`在`Cargo.toml`指定的是`1.80`,两者匹配是没问题的吧，会影响到打出来的包，不兼容其他版本？

**Comment by chrislearn** [comment]
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

你可以仔细阅读一下官方的说明

**Comment by immno** [comment]
我没看出官方说出的问题，我只想到两个场景：
1. 使用方如果使用低版本（比如`1.60`），但是`salvo`使用的是`1.80`，假设还使用了`1.60`不具备的一些特性，那使用方能正常使用和编译吗？
2. 我使用`1.82.0`并使用特有的api为现在的`salvo`提交了功能，但是`salvo`的`cargo.toml`声明还是`1.80`,这个版本如果被发布，客户端是低于`1.82`的话，正常使用和编译吗？

**Comment by chrislearn** [comment]
1. 版本低于 salvo 要求吗版本必定报错。
2. 你这种情况 salvo 的 ci 根本过不去。

强制客户必须用哪个版本 rust 是不合理的。如果他使用了多个 crates 而他们每一个强制用户使用的 rust 版本不一致，会是什么情况。
你可以去看一下其他的 web 库也都没有这个文件的。

**Comment by immno** [comment]
不是阿，只会在当前crate生效：
```
mno@happypeel:~/.rustup$ find . -maxdepth 2 -type d
.
./toolchains
./toolchains/1.67.1-x86_64-unknown-linux-gnu
./toolchains/1.77.0-x86_64-unknown-linux-gnu
./toolchains/nightly-x86_64-unknown-linux-gnu
./toolchains/1.65.0-x86_64-unknown-linux-gnu
./toolchains/1.75.0-x86_64-unknown-linux-gnu
./tmp
./downloads
./update-hashes
```
我在本地看能不能模拟一下，依赖一个具有`rust-toolchain.toml`的库，会不会影响当前库的`rustc`版本以及正常使用

**Comment by immno** [comment]
我创建了一个[salvo-toolchain-test](https://github.com/immno/salvo-toolchain-test)项目进行测试,我本地`salvo`的`rust-toolchain.toml`为（也可以使用[immno/salvo/tree/toolchain](https://github.com/immno/salvo/tree/toolchain)）：
```
[toolchain]
channel = "1.80"
components = ["cargo", "clippy", "rustfmt", "rust-docs", "rust-analyzer"]
```
每次测试前均删除`target`与`Cargo.lock`.
1. `salvo-toolchain-test`的`rust-toolchain.toml`设置为：
```
[toolchain]
channel = "1.65.0"
components = ["cargo", "clippy", "rustfmt", "rust-docs"]
```
![image](https://github.com/user-attachments/assets/3e4208c6-85da-4cf8-bfd5-75b08abc2d90)
编译不能通过。
2. `salvo-toolchain-test`的`rust-toolchain.toml`设置为：
```
[toolchain]
channel = "1.75.0"
components = ["cargo", "clippy", "rustfmt", "rust-docs"]
```
![image](https://github.com/user-attachments/assets/cbfc16f5-42e0-451b-9692-4799c946c7b7)
编译失败，`LazyLock`应该是rust`1.80`版本支持的。
3. `salvo-toolchain-test`的`rust-toolchain.toml`设置为：
```
[toolchain]
channel = "1.80.0"
components = ["cargo", "clippy", "rustfmt", "rust-docs"]
```
![image](https://github.com/user-attachments/assets/9ec28646-d848-4169-9733-f612a25a0211)
编译通过，正常运行。
4. `salvo-toolchain-test`的`rust-toolchain.toml`设置为：
```
[toolchain]
channel = "1.82.0"
components = ["cargo", "clippy", "rustfmt", "rust-docs"]
```
![image](https://github.com/user-attachments/assets/79969a2f-fe9d-48da-a483-bbbd81c851d0)
编译通过，正常运行。
因此，我认为对使用方的影响还是取决于`salvo`具体支持的MSRV (minimum supported rust version)是多少。如果项目中设置的`rust-version = "?`，`rust-toolchain.toml`与`Cargo.toml`中的`rust-version`匹配即可。

**Comment by chrislearn** [comment]
应该是所以的 crates 的配置里面忘记添加 rust-version 的配置了。加上后，如果版本达不到要求的最低版本号，会报错。

```
error: rustc 1.81.0 is not supported by the following package:
  salvo@0.74.1 requires rustc 1.82.0
```

**Comment by immno** [comment]
我怎么不理解了，salvo不是依赖1.80的吗，怎么又报依赖1.82了。。

**Comment by chrislearn** [comment]
> 我怎么不理解了，salvo不是依赖1.80的吗，怎么又报依赖1.82了。。

我只是本地测试随便写的值，应该是报 1.80

**Comment by immno** [comment]
哦哦
