### ISSUE TITLE
我在集成OpenApi功能的使用，QueryParam书写方式不支持

### ISSUE THREAD

**Issue by Austin-Patrician** [salvo-rs/salvo#992]
![image](https://github.com/user-attachments/assets/95322825-4442-4ef2-bfdf-6cbbce02b932)

**Comment by chrislearn** [comment]
请给最小可重现错误的库地址

**Comment by Austin-Patrician** [comment]
https://github.com/salvo-rs/salvo/blob/main/examples/oapi-hello/src/main.rs
![image](https://github.com/user-attachments/assets/5b8bbfa4-2977-400b-bc7b-f045e0648037)

**Comment by chrislearn** [comment]
所有的官方示例都是可以正常编译运行的。

**Comment by Austin-Patrician** [comment]
Is there any particular config in the cargo.toml ?
![image](https://github.com/user-attachments/assets/7bd21b76-9625-4771-a25d-db419587e5cc)
Is there enough to run this example? as you can see the screenshot i attach before, it looks good right.

**Comment by chrislearn** [comment]
你自己编译看看呢？编译报什么错？你那个只是编译器给你的错误提醒，不一定对。

**Comment by Austin-Patrician** [comment]
![image](https://github.com/user-attachments/assets/a981d533-6617-4377-8e8f-4cfe9614b9ad)

**Comment by Austin-Patrician** [comment]
麻烦等待一下，我新建一个demo

**Comment by Austin-Patrician** [comment]
我找到问题了，是以为我引用了下面的endpoint . 对了, 是不是现在rustrover还无法识别这个queryparam的写法
use salvo::oapi::endpoint;

**Comment by liucq200518** [comment]
我也遇到同样的问题，编译运行倒是没问题，看着有些别扭
